<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Análisis Exploratorio de Datos (EDA) | Análisis estadístico del efecto de la ceniza volante sobre la resistencia del concreto</title>
  <meta name="description" content="Análisis estadístico del efecto de la ceniza volante y el tiempo de curado sobre la resistencia a la compresión del concreto." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Análisis Exploratorio de Datos (EDA) | Análisis estadístico del efecto de la ceniza volante sobre la resistencia del concreto" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Análisis estadístico del efecto de la ceniza volante y el tiempo de curado sobre la resistencia a la compresión del concreto." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Análisis Exploratorio de Datos (EDA) | Análisis estadístico del efecto de la ceniza volante sobre la resistencia del concreto" />
  
  <meta name="twitter:description" content="Análisis estadístico del efecto de la ceniza volante y el tiempo de curado sobre la resistencia a la compresión del concreto." />
  

<meta name="author" content="Camilo Padilla &amp; Juan Campo" />


<meta name="date" content="2026-10-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Proyecto Final - Métodos Estadísticos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Presentación</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#estructura-del-documento"><i class="fa fa-check"></i><b>1.1</b> Estructura del Documento</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción y Objetivos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#contexto"><i class="fa fa-check"></i><b>2.1</b> Contexto</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#problem%C3%A1tica"><i class="fa fa-check"></i><b>2.2</b> Problemática</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#objetivos-del-proyecto"><i class="fa fa-check"></i><b>2.3</b> Objetivos del Proyecto</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="intro.html"><a href="intro.html#objetivo-general"><i class="fa fa-check"></i><b>2.3.1</b> Objetivo general</a></li>
<li class="chapter" data-level="2.3.2" data-path="intro.html"><a href="intro.html#objetivos-especificos"><i class="fa fa-check"></i><b>2.3.2</b> Objetivos especificos</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#justificaci%C3%B3n"><i class="fa fa-check"></i><b>2.4</b> Justificación</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="eda.html"><a href="eda.html"><i class="fa fa-check"></i><b>3</b> Análisis Exploratorio de Datos (EDA)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="eda.html"><a href="eda.html#dataset-y-ficha-tecnica"><i class="fa fa-check"></i><b>3.1</b> Dataset y ficha tecnica</a></li>
<li class="chapter" data-level="3.2" data-path="eda.html"><a href="eda.html#importamos-librerias"><i class="fa fa-check"></i><b>3.2</b> Importamos librerias</a></li>
<li class="chapter" data-level="3.3" data-path="eda.html"><a href="eda.html#carga-de-datos"><i class="fa fa-check"></i><b>3.3</b> Carga de Datos</a></li>
<li class="chapter" data-level="3.4" data-path="eda.html"><a href="eda.html#diccionario-de-variables"><i class="fa fa-check"></i><b>3.4</b> Diccionario de Variables</a></li>
<li class="chapter" data-level="3.5" data-path="eda.html"><a href="eda.html#exploraci%C3%B3n-del-data-set."><i class="fa fa-check"></i><b>3.5</b> Exploración del data set.</a></li>
<li class="chapter" data-level="3.6" data-path="eda.html"><a href="eda.html#calidad-y-estructura-de-los-datos"><i class="fa fa-check"></i><b>3.6</b> Calidad y estructura de los datos</a></li>
<li class="chapter" data-level="3.7" data-path="eda.html"><a href="eda.html#tabla-descriptiva-de-las-variables"><i class="fa fa-check"></i><b>3.7</b> Tabla descriptiva de las variables</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="eda.html"><a href="eda.html#exploraci%C3%B3n-de-la-variable-de-respuesta"><i class="fa fa-check"></i><b>3.7.1</b> Exploración de la variable de respuesta</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="eda.html"><a href="eda.html#anlisis-univariado-de-las-variables"><i class="fa fa-check"></i><b>3.8</b> Anlisis Univariado de las variables</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="eda.html"><a href="eda.html#analisis-boxplot-tiempo-de-curado"><i class="fa fa-check"></i><b>3.8.1</b> Analisis boxplot tiempo de curado</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="eda.html"><a href="eda.html#analisis-bivariado"><i class="fa fa-check"></i><b>3.9</b> Analisis Bivariado</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="eda.html"><a href="eda.html#creacion-de-nuevas-variables"><i class="fa fa-check"></i><b>3.9.1</b> Creacion de nuevas variables</a></li>
<li class="chapter" data-level="3.9.2" data-path="eda.html"><a href="eda.html#tabla-descriptiva-de-las-nuevas-variables"><i class="fa fa-check"></i><b>3.9.2</b> Tabla descriptiva de las nuevas variables</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="eda.html"><a href="eda.html#pruebas-de-normalidad"><i class="fa fa-check"></i><b>3.10</b> Pruebas de normalidad</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="eda.html"><a href="eda.html#validaci%C3%B3n-visual-q-q-plots"><i class="fa fa-check"></i><b>3.10.1</b> 2. VALIDACIÓN VISUAL (Q-Q PLOTS)</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/Juan-cmp/Metodos-estadististicos-proyecto" target="blank">Repositorio en GitHub</a></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis estadístico del efecto de la ceniza volante sobre la resistencia del concreto</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="eda" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> Análisis Exploratorio de Datos (EDA)<a href="eda.html#eda" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo analizamos las variables cuantitativas del dataset de Concrete Compressive Strength (Resistencia del Concreto).</p>
<div id="dataset-y-ficha-tecnica" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Dataset y ficha tecnica<a href="eda.html#dataset-y-ficha-tecnica" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p><strong>Fuente:</strong> UCI Machine Learning Repository (Donado por el Prof. I-Cheng Yeh, 2007).</p></li>
<li><p><strong>Área:</strong> Ingeniería Civil / Ciencia de Materiales.</p></li>
<li><p><strong>Número de Observaciones (</strong>N<strong>):</strong> 1,030 mezclas experimentales.</p></li>
<li><p><strong>Número de Variables:</strong> 9 variables cuantitativas (8 independientes + 1 dependiente).</p></li>
<li><p><strong>Valores Faltantes:</strong> Ninguno.</p></li>
</ul>
</div>
<div id="importamos-librerias" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Importamos librerias<a href="eda.html#importamos-librerias" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="eda.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-2"><a href="eda.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(moments) </span>
<span id="cb1-3"><a href="eda.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(patchwork) </span>
<span id="cb1-4"><a href="eda.html#cb1-4" tabindex="-1"></a><span class="fu">library</span>(GGally) </span>
<span id="cb1-5"><a href="eda.html#cb1-5" tabindex="-1"></a><span class="fu">library</span>(dplyr) </span>
<span id="cb1-6"><a href="eda.html#cb1-6" tabindex="-1"></a><span class="fu">library</span>(effsize) </span>
<span id="cb1-7"><a href="eda.html#cb1-7" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb1-8"><a href="eda.html#cb1-8" tabindex="-1"></a><span class="fu">library</span>(lmtest)   </span>
<span id="cb1-9"><a href="eda.html#cb1-9" tabindex="-1"></a><span class="fu">library</span>(car)      </span>
<span id="cb1-10"><a href="eda.html#cb1-10" tabindex="-1"></a><span class="fu">library</span>(janitor)  </span>
<span id="cb1-11"><a href="eda.html#cb1-11" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-12"><a href="eda.html#cb1-12" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div>
</div>
<div id="carga-de-datos" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Carga de Datos<a href="eda.html#carga-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="eda.html#cb2-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="eda.html#cb2-2" tabindex="-1"></a>Concrete_Data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;concrete+compressive+strength/Concrete_Data.xls&quot;</span>)</span>
<span id="cb2-3"><a href="eda.html#cb2-3" tabindex="-1"></a></span>
<span id="cb2-4"><a href="eda.html#cb2-4" tabindex="-1"></a>df<span class="ot">&lt;-</span> Concrete_Data</span></code></pre></div>
</div>
<div id="diccionario-de-variables" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Diccionario de Variables<a href="eda.html#diccionario-de-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Aclaramos que cada observacion representa un ensayo de laboratorio con una receta individual con ingredientes mezclados para hacer un metro cubico de cemento, el tiempo que se dejo reposar y la fuerza que resistio.</p>
<p>Todas las variables son cuantitativas continuas:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="eda.html#cb3-1" tabindex="-1"></a>diccionario_variables <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-2"><a href="eda.html#cb3-2" tabindex="-1"></a>  <span class="at">variable =</span> <span class="fu">c</span>(</span>
<span id="cb3-3"><a href="eda.html#cb3-3" tabindex="-1"></a>    <span class="st">&quot;Cemento&quot;</span>, <span class="st">&quot;Escoria de alto horno&quot;</span>, <span class="st">&quot;Ceniza volante&quot;</span>, <span class="st">&quot;Agua&quot;</span>,</span>
<span id="cb3-4"><a href="eda.html#cb3-4" tabindex="-1"></a>    <span class="st">&quot;Superplastificante&quot;</span>, <span class="st">&quot;Agregado Grueso&quot;</span>, <span class="st">&quot;Agregado Fino&quot;</span>, <span class="st">&quot;Edad&quot;</span>, <span class="st">&quot;Resistencia&quot;</span></span>
<span id="cb3-5"><a href="eda.html#cb3-5" tabindex="-1"></a>  ),</span>
<span id="cb3-6"><a href="eda.html#cb3-6" tabindex="-1"></a>  <span class="at">nombre_dataset =</span> <span class="fu">c</span>(</span>
<span id="cb3-7"><a href="eda.html#cb3-7" tabindex="-1"></a>    <span class="st">&quot;Cement&quot;</span>, <span class="st">&quot;Blast_Furnace_Slag&quot;</span>, <span class="st">&quot;Fly_Ash&quot;</span>, <span class="st">&quot;Water&quot;</span>, <span class="st">&quot;Superplasticizer&quot;</span>,</span>
<span id="cb3-8"><a href="eda.html#cb3-8" tabindex="-1"></a>    <span class="st">&quot;Coarse_Aggregate&quot;</span>, <span class="st">&quot;Fine_Aggregate&quot;</span>, <span class="st">&quot;Age&quot;</span>, <span class="st">&quot;Concrete_Compressive_Strength&quot;</span></span>
<span id="cb3-9"><a href="eda.html#cb3-9" tabindex="-1"></a>  ),</span>
<span id="cb3-10"><a href="eda.html#cb3-10" tabindex="-1"></a>  <span class="at">tipo =</span> <span class="fu">c</span>(</span>
<span id="cb3-11"><a href="eda.html#cb3-11" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="st">&quot;Entrada (Indep.)&quot;</span>, <span class="dv">8</span>), <span class="st">&quot;Salida (Dependiente)&quot;</span></span>
<span id="cb3-12"><a href="eda.html#cb3-12" tabindex="-1"></a>  ),</span>
<span id="cb3-13"><a href="eda.html#cb3-13" tabindex="-1"></a>  <span class="at">unidad =</span> <span class="fu">c</span>(</span>
<span id="cb3-14"><a href="eda.html#cb3-14" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="st">&quot;kg/m^3&quot;</span>, <span class="dv">7</span>), <span class="st">&quot;Dias (1 a 365)&quot;</span>, <span class="st">&quot;MPa&quot;</span></span>
<span id="cb3-15"><a href="eda.html#cb3-15" tabindex="-1"></a>  ),</span>
<span id="cb3-16"><a href="eda.html#cb3-16" tabindex="-1"></a>  <span class="at">descripcion =</span> <span class="fu">c</span>(</span>
<span id="cb3-17"><a href="eda.html#cb3-17" tabindex="-1"></a>    <span class="st">&quot;Componente aglutinante principal.&quot;</span>,</span>
<span id="cb3-18"><a href="eda.html#cb3-18" tabindex="-1"></a>    <span class="st">&quot;Subproducto siderurgico que mejora durabilidad.&quot;</span>,</span>
<span id="cb3-19"><a href="eda.html#cb3-19" tabindex="-1"></a>    <span class="st">&quot;Subproducto de centrales termicas.&quot;</span>,</span>
<span id="cb3-20"><a href="eda.html#cb3-20" tabindex="-1"></a>    <span class="st">&quot;Cantidad de agua.&quot;</span>,</span>
<span id="cb3-21"><a href="eda.html#cb3-21" tabindex="-1"></a>    <span class="st">&quot;Aditivo quimico que reduce necesidad de agua.&quot;</span>,</span>
<span id="cb3-22"><a href="eda.html#cb3-22" tabindex="-1"></a>    <span class="st">&quot;Grava / Piedra chancada.&quot;</span>,</span>
<span id="cb3-23"><a href="eda.html#cb3-23" tabindex="-1"></a>    <span class="st">&quot;Arena.&quot;</span>,</span>
<span id="cb3-24"><a href="eda.html#cb3-24" tabindex="-1"></a>    <span class="st">&quot;Tiempo de maduracion/curado del concreto.&quot;</span>,</span>
<span id="cb3-25"><a href="eda.html#cb3-25" tabindex="-1"></a>    <span class="st">&quot;Resistencia final a la compresion.&quot;</span></span>
<span id="cb3-26"><a href="eda.html#cb3-26" tabindex="-1"></a>  )</span>
<span id="cb3-27"><a href="eda.html#cb3-27" tabindex="-1"></a>)</span>
<span id="cb3-28"><a href="eda.html#cb3-28" tabindex="-1"></a></span>
<span id="cb3-29"><a href="eda.html#cb3-29" tabindex="-1"></a>diccionario_variables <span class="sc">|&gt;</span></span>
<span id="cb3-30"><a href="eda.html#cb3-30" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb3-31"><a href="eda.html#cb3-31" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Diccionario de variables del conjunto de datos&quot;</span>,</span>
<span id="cb3-32"><a href="eda.html#cb3-32" tabindex="-1"></a>    <span class="at">format =</span> <span class="fu">ifelse</span>(knitr<span class="sc">::</span><span class="fu">is_latex_output</span>(), <span class="st">&quot;latex&quot;</span>, <span class="st">&quot;html&quot;</span>)</span>
<span id="cb3-33"><a href="eda.html#cb3-33" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-34"><a href="eda.html#cb3-34" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb3-35"><a href="eda.html#cb3-35" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb3-36"><a href="eda.html#cb3-36" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hold_position&quot;</span>, <span class="st">&quot;scale_down&quot;</span>),</span>
<span id="cb3-37"><a href="eda.html#cb3-37" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb3-38"><a href="eda.html#cb3-38" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb3-39"><a href="eda.html#cb3-39" tabindex="-1"></a>  )</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabla-diccionario">Table 3.1: </span>Diccionario de variables del conjunto de datos
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:left;">
nombre_dataset
</th>
<th style="text-align:left;">
tipo
</th>
<th style="text-align:left;">
unidad
</th>
<th style="text-align:left;">
descripcion
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Cemento
</td>
<td style="text-align:left;">
Cement
</td>
<td style="text-align:left;">
Entrada (Indep.)
</td>
<td style="text-align:left;">
kg/m^3
</td>
<td style="text-align:left;">
Componente aglutinante principal.
</td>
</tr>
<tr>
<td style="text-align:left;">
Escoria de alto horno
</td>
<td style="text-align:left;">
Blast_Furnace_Slag
</td>
<td style="text-align:left;">
Entrada (Indep.)
</td>
<td style="text-align:left;">
kg/m^3
</td>
<td style="text-align:left;">
Subproducto siderurgico que mejora durabilidad.
</td>
</tr>
<tr>
<td style="text-align:left;">
Ceniza volante
</td>
<td style="text-align:left;">
Fly_Ash
</td>
<td style="text-align:left;">
Entrada (Indep.)
</td>
<td style="text-align:left;">
kg/m^3
</td>
<td style="text-align:left;">
Subproducto de centrales termicas.
</td>
</tr>
<tr>
<td style="text-align:left;">
Agua
</td>
<td style="text-align:left;">
Water
</td>
<td style="text-align:left;">
Entrada (Indep.)
</td>
<td style="text-align:left;">
kg/m^3
</td>
<td style="text-align:left;">
Cantidad de agua.
</td>
</tr>
<tr>
<td style="text-align:left;">
Superplastificante
</td>
<td style="text-align:left;">
Superplasticizer
</td>
<td style="text-align:left;">
Entrada (Indep.)
</td>
<td style="text-align:left;">
kg/m^3
</td>
<td style="text-align:left;">
Aditivo quimico que reduce necesidad de agua.
</td>
</tr>
<tr>
<td style="text-align:left;">
Agregado Grueso
</td>
<td style="text-align:left;">
Coarse_Aggregate
</td>
<td style="text-align:left;">
Entrada (Indep.)
</td>
<td style="text-align:left;">
kg/m^3
</td>
<td style="text-align:left;">
Grava / Piedra chancada.
</td>
</tr>
<tr>
<td style="text-align:left;">
Agregado Fino
</td>
<td style="text-align:left;">
Fine_Aggregate
</td>
<td style="text-align:left;">
Entrada (Indep.)
</td>
<td style="text-align:left;">
kg/m^3
</td>
<td style="text-align:left;">
Arena.
</td>
</tr>
<tr>
<td style="text-align:left;">
Edad
</td>
<td style="text-align:left;">
Age
</td>
<td style="text-align:left;">
Entrada (Indep.)
</td>
<td style="text-align:left;">
Dias (1 a 365)
</td>
<td style="text-align:left;">
Tiempo de maduracion/curado del concreto.
</td>
</tr>
<tr>
<td style="text-align:left;">
Resistencia
</td>
<td style="text-align:left;">
Concrete_Compressive_Strength
</td>
<td style="text-align:left;">
Salida (Dependiente)
</td>
<td style="text-align:left;">
MPa
</td>
<td style="text-align:left;">
Resistencia final a la compresion.
</td>
</tr>
</tbody>
</table>
</div>
<div id="exploración-del-data-set." class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Exploración del data set.<a href="eda.html#exploraci%C3%B3n-del-data-set." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Resumimos los nombres de las variables</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="eda.html#cb4-1" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="eda.html#cb4-2" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb4-3"><a href="eda.html#cb4-3" tabindex="-1"></a>    <span class="at">cemento          =</span> <span class="st">`</span><span class="at">Cement (component 1)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb4-4"><a href="eda.html#cb4-4" tabindex="-1"></a>    <span class="at">escoria          =</span> <span class="st">`</span><span class="at">Blast Furnace Slag (component 2)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb4-5"><a href="eda.html#cb4-5" tabindex="-1"></a>    <span class="at">ceniza           =</span> <span class="st">`</span><span class="at">Fly Ash (component 3)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb4-6"><a href="eda.html#cb4-6" tabindex="-1"></a>    <span class="at">agua             =</span> <span class="st">`</span><span class="at">Water  (component 4)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb4-7"><a href="eda.html#cb4-7" tabindex="-1"></a>    <span class="at">superplast       =</span> <span class="st">`</span><span class="at">Superplasticizer (component 5)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb4-8"><a href="eda.html#cb4-8" tabindex="-1"></a>    <span class="at">agregado_grueso  =</span> <span class="st">`</span><span class="at">Coarse Aggregate  (component 6)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb4-9"><a href="eda.html#cb4-9" tabindex="-1"></a>    <span class="at">agregado_fino    =</span> <span class="st">`</span><span class="at">Fine Aggregate (component 7)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb4-10"><a href="eda.html#cb4-10" tabindex="-1"></a>    <span class="at">edad             =</span> <span class="st">`</span><span class="at">Age (day)</span><span class="st">`</span>,</span>
<span id="cb4-11"><a href="eda.html#cb4-11" tabindex="-1"></a>    <span class="at">resistencia      =</span> <span class="st">`</span><span class="at">Concrete compressive strength(MPa, megapascals)</span><span class="st">`</span></span>
<span id="cb4-12"><a href="eda.html#cb4-12" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div id="calidad-y-estructura-de-los-datos" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Calidad y estructura de los datos<a href="eda.html#calidad-y-estructura-de-los-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="eda.html#cb5-1" tabindex="-1"></a>calidad_datos <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb5-2"><a href="eda.html#cb5-2" tabindex="-1"></a>  <span class="at">variable =</span> <span class="fu">names</span>(df_clean),</span>
<span id="cb5-3"><a href="eda.html#cb5-3" tabindex="-1"></a>  <span class="at">clase =</span> <span class="fu">map_chr</span>(df_clean, <span class="sc">~</span> <span class="fu">class</span>(.x)[<span class="dv">1</span>]),</span>
<span id="cb5-4"><a href="eda.html#cb5-4" tabindex="-1"></a>  <span class="at">tipo =</span> <span class="fu">map_chr</span>(df_clean, typeof),</span>
<span id="cb5-5"><a href="eda.html#cb5-5" tabindex="-1"></a>  <span class="at">faltantes =</span> <span class="fu">map_int</span>(df_clean, <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.x))),</span>
<span id="cb5-6"><a href="eda.html#cb5-6" tabindex="-1"></a>  <span class="at">valores_unicos =</span> <span class="fu">map_int</span>(df_clean, n_distinct)</span>
<span id="cb5-7"><a href="eda.html#cb5-7" tabindex="-1"></a>)</span>
<span id="cb5-8"><a href="eda.html#cb5-8" tabindex="-1"></a></span>
<span id="cb5-9"><a href="eda.html#cb5-9" tabindex="-1"></a>calidad_datos <span class="sc">|&gt;</span></span>
<span id="cb5-10"><a href="eda.html#cb5-10" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb5-11"><a href="eda.html#cb5-11" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Calidad y estructura de los datos&quot;</span>,</span>
<span id="cb5-12"><a href="eda.html#cb5-12" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span>,</span>
<span id="cb5-13"><a href="eda.html#cb5-13" tabindex="-1"></a>    <span class="at">format =</span> <span class="fu">ifelse</span>(knitr<span class="sc">::</span><span class="fu">is_latex_output</span>(), <span class="st">&quot;latex&quot;</span>, <span class="st">&quot;html&quot;</span>)</span>
<span id="cb5-14"><a href="eda.html#cb5-14" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb5-15"><a href="eda.html#cb5-15" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb5-16"><a href="eda.html#cb5-16" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb5-17"><a href="eda.html#cb5-17" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hold_position&quot;</span>),</span>
<span id="cb5-18"><a href="eda.html#cb5-18" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb5-19"><a href="eda.html#cb5-19" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb5-20"><a href="eda.html#cb5-20" tabindex="-1"></a>  )</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:calidad-datos">Table 3.2: </span>Calidad y estructura de los datos
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:left;">
clase
</th>
<th style="text-align:left;">
tipo
</th>
<th style="text-align:right;">
faltantes
</th>
<th style="text-align:right;">
valores_unicos
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cemento
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
escoria
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
187
</td>
</tr>
<tr>
<td style="text-align:left;">
ceniza
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
163
</td>
</tr>
<tr>
<td style="text-align:left;">
agua
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
205
</td>
</tr>
<tr>
<td style="text-align:left;">
superplast
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
155
</td>
</tr>
<tr>
<td style="text-align:left;">
agregado_grueso
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
284
</td>
</tr>
<tr>
<td style="text-align:left;">
agregado_fino
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
304
</td>
</tr>
<tr>
<td style="text-align:left;">
edad
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:left;">
resistencia
</td>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
double
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
938
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="eda.html#cb6-1" tabindex="-1"></a>duplicados <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-2"><a href="eda.html#cb6-2" tabindex="-1"></a>  <span class="at">indicador =</span> <span class="st">&quot;Filas duplicadas&quot;</span>,</span>
<span id="cb6-3"><a href="eda.html#cb6-3" tabindex="-1"></a>  <span class="at">cantidad =</span> <span class="fu">sum</span>(<span class="fu">duplicated</span>(df_clean))</span>
<span id="cb6-4"><a href="eda.html#cb6-4" tabindex="-1"></a>)</span>
<span id="cb6-5"><a href="eda.html#cb6-5" tabindex="-1"></a></span>
<span id="cb6-6"><a href="eda.html#cb6-6" tabindex="-1"></a>duplicados <span class="sc">|&gt;</span></span>
<span id="cb6-7"><a href="eda.html#cb6-7" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb6-8"><a href="eda.html#cb6-8" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Filas duplicadas del conjunto de datos&quot;</span>,</span>
<span id="cb6-9"><a href="eda.html#cb6-9" tabindex="-1"></a>    <span class="at">format =</span> <span class="fu">ifelse</span>(knitr<span class="sc">::</span><span class="fu">is_latex_output</span>(), <span class="st">&quot;latex&quot;</span>, <span class="st">&quot;html&quot;</span>)</span>
<span id="cb6-10"><a href="eda.html#cb6-10" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb6-11"><a href="eda.html#cb6-11" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb6-12"><a href="eda.html#cb6-12" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb6-13"><a href="eda.html#cb6-13" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hold_position&quot;</span>),</span>
<span id="cb6-14"><a href="eda.html#cb6-14" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-15"><a href="eda.html#cb6-15" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb6-16"><a href="eda.html#cb6-16" tabindex="-1"></a>  )</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:calidad-datos">Table 3.2: </span>Filas duplicadas del conjunto de datos
</caption>
<thead>
<tr>
<th style="text-align:left;">
indicador
</th>
<th style="text-align:right;">
cantidad
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Filas duplicadas
</td>
<td style="text-align:right;">
25
</td>
</tr>
</tbody>
</table>
</div>
<div id="tabla-descriptiva-de-las-variables" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> Tabla descriptiva de las variables<a href="eda.html#tabla-descriptiva-de-las-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="eda.html#cb7-1" tabindex="-1"></a>tabla_descriptiva <span class="ot">&lt;-</span> df_clean <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="eda.html#cb7-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb7-3"><a href="eda.html#cb7-3" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb7-4"><a href="eda.html#cb7-4" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb7-5"><a href="eda.html#cb7-5" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb7-6"><a href="eda.html#cb7-6" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-7"><a href="eda.html#cb7-7" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">|&gt;</span></span>
<span id="cb7-8"><a href="eda.html#cb7-8" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-9"><a href="eda.html#cb7-9" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(valor)),</span>
<span id="cb7-10"><a href="eda.html#cb7-10" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-11"><a href="eda.html#cb7-11" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-12"><a href="eda.html#cb7-12" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-13"><a href="eda.html#cb7-13" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">IQR</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-14"><a href="eda.html#cb7-14" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-15"><a href="eda.html#cb7-15" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(valor, <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-16"><a href="eda.html#cb7-16" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-17"><a href="eda.html#cb7-17" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-18"><a href="eda.html#cb7-18" tabindex="-1"></a>    <span class="at">asim =</span> <span class="fu">skewness</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-19"><a href="eda.html#cb7-19" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-20"><a href="eda.html#cb7-20" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb7-21"><a href="eda.html#cb7-21" tabindex="-1"></a>  )</span>
<span id="cb7-22"><a href="eda.html#cb7-22" tabindex="-1"></a></span>
<span id="cb7-23"><a href="eda.html#cb7-23" tabindex="-1"></a>tabla_descriptiva <span class="sc">|&gt;</span></span>
<span id="cb7-24"><a href="eda.html#cb7-24" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb7-25"><a href="eda.html#cb7-25" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Estadisticas descriptivas de las nueve variables&quot;</span>,</span>
<span id="cb7-26"><a href="eda.html#cb7-26" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb7-27"><a href="eda.html#cb7-27" tabindex="-1"></a>    <span class="at">format =</span> <span class="fu">ifelse</span>(knitr<span class="sc">::</span><span class="fu">is_latex_output</span>(), <span class="st">&quot;latex&quot;</span>, <span class="st">&quot;html&quot;</span>)</span>
<span id="cb7-28"><a href="eda.html#cb7-28" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-29"><a href="eda.html#cb7-29" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb7-30"><a href="eda.html#cb7-30" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb7-31"><a href="eda.html#cb7-31" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hold_position&quot;</span>, <span class="st">&quot;scale_down&quot;</span>),</span>
<span id="cb7-32"><a href="eda.html#cb7-32" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb7-33"><a href="eda.html#cb7-33" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb7-34"><a href="eda.html#cb7-34" tabindex="-1"></a>  )</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabla-descriptiva">Table 3.3: </span>Estadisticas descriptivas de las nueve variables
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
mediana
</th>
<th style="text-align:right;">
RIC
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
asim
</th>
<th style="text-align:right;">
curtosis
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
agregado_fino
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
773.579
</td>
<td style="text-align:right;">
80.175
</td>
<td style="text-align:right;">
779.510
</td>
<td style="text-align:right;">
93.050
</td>
<td style="text-align:right;">
730.950
</td>
<td style="text-align:right;">
824.000
</td>
<td style="text-align:right;">
594.000
</td>
<td style="text-align:right;">
992.600
</td>
<td style="text-align:right;">
-0.253
</td>
<td style="text-align:right;">
2.893
</td>
</tr>
<tr>
<td style="text-align:left;">
agregado_grueso
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
972.919
</td>
<td style="text-align:right;">
77.754
</td>
<td style="text-align:right;">
968.000
</td>
<td style="text-align:right;">
97.400
</td>
<td style="text-align:right;">
932.000
</td>
<td style="text-align:right;">
1029.400
</td>
<td style="text-align:right;">
801.000
</td>
<td style="text-align:right;">
1145.000
</td>
<td style="text-align:right;">
-0.040
</td>
<td style="text-align:right;">
2.398
</td>
</tr>
<tr>
<td style="text-align:left;">
agua
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
181.566
</td>
<td style="text-align:right;">
21.356
</td>
<td style="text-align:right;">
185.000
</td>
<td style="text-align:right;">
27.100
</td>
<td style="text-align:right;">
164.900
</td>
<td style="text-align:right;">
192.000
</td>
<td style="text-align:right;">
121.750
</td>
<td style="text-align:right;">
247.000
</td>
<td style="text-align:right;">
0.074
</td>
<td style="text-align:right;">
3.116
</td>
</tr>
<tr>
<td style="text-align:left;">
cemento
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
281.166
</td>
<td style="text-align:right;">
104.507
</td>
<td style="text-align:right;">
272.900
</td>
<td style="text-align:right;">
157.625
</td>
<td style="text-align:right;">
192.375
</td>
<td style="text-align:right;">
350.000
</td>
<td style="text-align:right;">
102.000
</td>
<td style="text-align:right;">
540.000
</td>
<td style="text-align:right;">
0.509
</td>
<td style="text-align:right;">
2.476
</td>
</tr>
<tr>
<td style="text-align:left;">
ceniza
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
54.187
</td>
<td style="text-align:right;">
63.996
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
118.270
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
118.270
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
200.100
</td>
<td style="text-align:right;">
0.537
</td>
<td style="text-align:right;">
1.672
</td>
</tr>
<tr>
<td style="text-align:left;">
edad
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
45.662
</td>
<td style="text-align:right;">
63.170
</td>
<td style="text-align:right;">
28.000
</td>
<td style="text-align:right;">
49.000
</td>
<td style="text-align:right;">
7.000
</td>
<td style="text-align:right;">
56.000
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
365.000
</td>
<td style="text-align:right;">
3.264
</td>
<td style="text-align:right;">
15.104
</td>
</tr>
<tr>
<td style="text-align:left;">
escoria
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
73.895
</td>
<td style="text-align:right;">
86.279
</td>
<td style="text-align:right;">
22.000
</td>
<td style="text-align:right;">
142.950
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
142.950
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
359.400
</td>
<td style="text-align:right;">
0.800
</td>
<td style="text-align:right;">
2.489
</td>
</tr>
<tr>
<td style="text-align:left;">
resistencia
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
35.818
</td>
<td style="text-align:right;">
16.706
</td>
<td style="text-align:right;">
34.443
</td>
<td style="text-align:right;">
22.429
</td>
<td style="text-align:right;">
23.707
</td>
<td style="text-align:right;">
46.136
</td>
<td style="text-align:right;">
2.332
</td>
<td style="text-align:right;">
82.599
</td>
<td style="text-align:right;">
0.416
</td>
<td style="text-align:right;">
2.682
</td>
</tr>
<tr>
<td style="text-align:left;">
superplast
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
6.203
</td>
<td style="text-align:right;">
5.973
</td>
<td style="text-align:right;">
6.350
</td>
<td style="text-align:right;">
10.160
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
10.160
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
32.200
</td>
<td style="text-align:right;">
0.907
</td>
<td style="text-align:right;">
4.401
</td>
</tr>
</tbody>
</table>
<div id="exploración-de-la-variable-de-respuesta" class="section level3 hasAnchor" number="3.7.1">
<h3><span class="header-section-number">3.7.1</span> Exploración de la variable de respuesta<a href="eda.html#exploraci%C3%B3n-de-la-variable-de-respuesta" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="eda.html#cb8-1" tabindex="-1"></a>tabla_resistencia <span class="ot">&lt;-</span> df_clean <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(resistencia),</span>
<span id="cb8-2"><a href="eda.html#cb8-2" tabindex="-1"></a>                 <span class="at">media =</span> <span class="fu">mean</span>(resistencia),</span>
<span id="cb8-3"><a href="eda.html#cb8-3" tabindex="-1"></a>                 <span class="at">sd =</span> <span class="fu">sd</span>(resistencia),</span>
<span id="cb8-4"><a href="eda.html#cb8-4" tabindex="-1"></a>                 <span class="at">mediana =</span> <span class="fu">median</span>(resistencia),</span>
<span id="cb8-5"><a href="eda.html#cb8-5" tabindex="-1"></a>                 <span class="at">RIC =</span> <span class="fu">IQR</span>(resistencia),</span>
<span id="cb8-6"><a href="eda.html#cb8-6" tabindex="-1"></a>                 <span class="at">Q1 =</span> <span class="fu">quantile</span>(resistencia, <span class="fl">0.25</span>),</span>
<span id="cb8-7"><a href="eda.html#cb8-7" tabindex="-1"></a>                 <span class="at">Q3 =</span> <span class="fu">quantile</span>(resistencia, <span class="fl">0.75</span>),</span>
<span id="cb8-8"><a href="eda.html#cb8-8" tabindex="-1"></a>                 <span class="at">minimo =</span> <span class="fu">min</span>(resistencia),</span>
<span id="cb8-9"><a href="eda.html#cb8-9" tabindex="-1"></a>                 <span class="at">maximo =</span> <span class="fu">max</span>(resistencia),</span>
<span id="cb8-10"><a href="eda.html#cb8-10" tabindex="-1"></a>                 <span class="at">asim =</span> <span class="fu">skewness</span>(resistencia),</span>
<span id="cb8-11"><a href="eda.html#cb8-11" tabindex="-1"></a>                 <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(resistencia))</span>
<span id="cb8-12"><a href="eda.html#cb8-12" tabindex="-1"></a></span>
<span id="cb8-13"><a href="eda.html#cb8-13" tabindex="-1"></a>tabla_resistencia <span class="sc">|&gt;</span></span>
<span id="cb8-14"><a href="eda.html#cb8-14" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb8-15"><a href="eda.html#cb8-15" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Estadisticas descriptivas de la resistencia a la compresion&quot;</span>,</span>
<span id="cb8-16"><a href="eda.html#cb8-16" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb8-17"><a href="eda.html#cb8-17" tabindex="-1"></a>    <span class="at">format =</span> <span class="fu">ifelse</span>(knitr<span class="sc">::</span><span class="fu">is_latex_output</span>(), <span class="st">&quot;latex&quot;</span>, <span class="st">&quot;html&quot;</span>)</span>
<span id="cb8-18"><a href="eda.html#cb8-18" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb8-19"><a href="eda.html#cb8-19" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb8-20"><a href="eda.html#cb8-20" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb8-21"><a href="eda.html#cb8-21" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hold_position&quot;</span>, <span class="st">&quot;scale_down&quot;</span>),</span>
<span id="cb8-22"><a href="eda.html#cb8-22" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb8-23"><a href="eda.html#cb8-23" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb8-24"><a href="eda.html#cb8-24" tabindex="-1"></a>  )</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:Concrete Compressive strenght)Estadisticas descriptivas de la resistencia a la compresion
</caption>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
mediana
</th>
<th style="text-align:right;">
RIC
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
asim
</th>
<th style="text-align:right;">
curtosis
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
35.818
</td>
<td style="text-align:right;">
16.706
</td>
<td style="text-align:right;">
34.443
</td>
<td style="text-align:right;">
22.429
</td>
<td style="text-align:right;">
23.707
</td>
<td style="text-align:right;">
46.136
</td>
<td style="text-align:right;">
2.332
</td>
<td style="text-align:right;">
82.599
</td>
<td style="text-align:right;">
0.416
</td>
<td style="text-align:right;">
2.682
</td>
</tr>
</tbody>
</table>
<p>Vemos que las 1030 observaciones de mezclas de concreto, tienen una resistencia de comprension de 35.817 MPa, con una desviación estándar de 16.70 MPa. Además, el 50% de las mezclas tienen una resistencia igual o menor a 34.442 MPa. Además, se observa una mezcla de concreto experimental con resistencia de 85.59 MPa siendo esta la observación con mayor Resistencia final a la compresión y otras con la minima resistencia entre las observaciones con 2.33 MPa.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="eda.html#cb9-1" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span>
<span id="cb9-2"><a href="eda.html#cb9-2" tabindex="-1"></a>df_clean <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="eda.html#cb9-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> resistencia)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="eda.html#cb9-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb9-5"><a href="eda.html#cb9-5" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb9-6"><a href="eda.html#cb9-6" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="dv">2</span>,</span>
<span id="cb9-7"><a href="eda.html#cb9-7" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;darkblue&quot;</span>,</span>
<span id="cb9-8"><a href="eda.html#cb9-8" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb9-9"><a href="eda.html#cb9-9" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb9-10"><a href="eda.html#cb9-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-11"><a href="eda.html#cb9-11" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb9-12"><a href="eda.html#cb9-12" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-13"><a href="eda.html#cb9-13" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de la resistencia del concreto&quot;</span>,</span>
<span id="cb9-14"><a href="eda.html#cb9-14" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia&quot;</span>,</span>
<span id="cb9-15"><a href="eda.html#cb9-15" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span></span>
<span id="cb9-16"><a href="eda.html#cb9-16" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-17"><a href="eda.html#cb9-17" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-3-1.png" alt="" width="672" style="display: block; margin: auto;" />
la resistencia muestra una distribución con forma parecida a una <strong>simétrica con forma de campana</strong>, centrada en torno a los <span class="math inline">\(35\text{ MPa}\)</span> y abarcando un rango desde los <span class="math inline">\(2.3\)</span> hasta los <span class="math inline">\(82.6\text{ MPa}\)</span>. La curva de densidad sugiere un comportamiento cercano a la <strong>distribución normal</strong>, reflejando una muestra equilibrada que abarca desde concretos convencionales hasta mezclas de alto rendimiento.
## Exploracion de las varibles independientes</p>
<p>Creamos la siguiente tabla para observar de forma descriptiva las variables independientes que analizaremos y asi complementar el analisis de los boxplots con ella.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="eda.html#cb10-1" tabindex="-1"></a>tabla_independientes <span class="ot">&lt;-</span> df_clean <span class="sc">|&gt;</span> <span class="fu">select</span>(ceniza, edad) <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="eda.html#cb10-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb10-3"><a href="eda.html#cb10-3" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb10-4"><a href="eda.html#cb10-4" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&#39;variables&#39;</span>,</span>
<span id="cb10-5"><a href="eda.html#cb10-5" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&#39;valor&#39;</span></span>
<span id="cb10-6"><a href="eda.html#cb10-6" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb10-7"><a href="eda.html#cb10-7" tabindex="-1"></a>  <span class="fu">group_by</span>(variables) <span class="sc">|&gt;</span> </span>
<span id="cb10-8"><a href="eda.html#cb10-8" tabindex="-1"></a>             <span class="fu">summarise</span>(    </span>
<span id="cb10-9"><a href="eda.html#cb10-9" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(valor),</span>
<span id="cb10-10"><a href="eda.html#cb10-10" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">round</span>(<span class="fu">mean</span>(valor), <span class="dv">3</span>),</span>
<span id="cb10-11"><a href="eda.html#cb10-11" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">round</span>(<span class="fu">sd</span>(valor),<span class="dv">3</span>),</span>
<span id="cb10-12"><a href="eda.html#cb10-12" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">round</span>(<span class="fu">median</span>(valor), <span class="dv">3</span>),</span>
<span id="cb10-13"><a href="eda.html#cb10-13" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">round</span>(<span class="fu">IQR</span>(valor), <span class="dv">3</span>),</span>
<span id="cb10-14"><a href="eda.html#cb10-14" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(valor, <span class="fl">0.25</span>), <span class="dv">3</span>),</span>
<span id="cb10-15"><a href="eda.html#cb10-15" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(valor, <span class="fl">0.75</span>), <span class="dv">3</span>),</span>
<span id="cb10-16"><a href="eda.html#cb10-16" tabindex="-1"></a>    <span class="at">minimo  =</span> <span class="fu">round</span>(<span class="fu">min</span>(valor), <span class="dv">3</span>),</span>
<span id="cb10-17"><a href="eda.html#cb10-17" tabindex="-1"></a>    <span class="at">maximo  =</span> <span class="fu">round</span>(<span class="fu">max</span>(valor), <span class="dv">3</span>),</span>
<span id="cb10-18"><a href="eda.html#cb10-18" tabindex="-1"></a>    <span class="at">asim    =</span> <span class="fu">round</span>(<span class="fu">skewness</span>(valor), <span class="dv">3</span>),</span>
<span id="cb10-19"><a href="eda.html#cb10-19" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">round</span>(<span class="fu">kurtosis</span>(valor), <span class="dv">3</span>))</span>
<span id="cb10-20"><a href="eda.html#cb10-20" tabindex="-1"></a></span>
<span id="cb10-21"><a href="eda.html#cb10-21" tabindex="-1"></a>tabla_independientes <span class="sc">|&gt;</span></span>
<span id="cb10-22"><a href="eda.html#cb10-22" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb10-23"><a href="eda.html#cb10-23" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Estadisticas descriptivas de ceniza volante y edad&quot;</span>,</span>
<span id="cb10-24"><a href="eda.html#cb10-24" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb10-25"><a href="eda.html#cb10-25" tabindex="-1"></a>    <span class="at">format =</span> <span class="fu">ifelse</span>(knitr<span class="sc">::</span><span class="fu">is_latex_output</span>(), <span class="st">&quot;latex&quot;</span>, <span class="st">&quot;html&quot;</span>)</span>
<span id="cb10-26"><a href="eda.html#cb10-26" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb10-27"><a href="eda.html#cb10-27" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb10-28"><a href="eda.html#cb10-28" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb10-29"><a href="eda.html#cb10-29" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hold_position&quot;</span>, <span class="st">&quot;scale_down&quot;</span>),</span>
<span id="cb10-30"><a href="eda.html#cb10-30" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb10-31"><a href="eda.html#cb10-31" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb10-32"><a href="eda.html#cb10-32" tabindex="-1"></a>  )</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-4">Table 3.4: </span>Estadisticas descriptivas de ceniza volante y edad
</caption>
<thead>
<tr>
<th style="text-align:left;">
variables
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
mediana
</th>
<th style="text-align:right;">
RIC
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
asim
</th>
<th style="text-align:right;">
curtosis
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ceniza
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
54.187
</td>
<td style="text-align:right;">
63.996
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
118.27
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
118.27
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
200.1
</td>
<td style="text-align:right;">
0.537
</td>
<td style="text-align:right;">
1.672
</td>
</tr>
<tr>
<td style="text-align:left;">
edad
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
45.662
</td>
<td style="text-align:right;">
63.170
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
49.00
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
56.00
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
365.0
</td>
<td style="text-align:right;">
3.264
</td>
<td style="text-align:right;">
15.104
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="eda.html#cb11-1" tabindex="-1"></a>df_clean <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="eda.html#cb11-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ceniza)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="eda.html#cb11-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb11-4"><a href="eda.html#cb11-4" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb11-5"><a href="eda.html#cb11-5" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="dv">10</span>,           <span class="co"># Intervalos de 10 kg/m^3</span></span>
<span id="cb11-6"><a href="eda.html#cb11-6" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;#d95f02&quot;</span>,        <span class="co"># Tono naranja / teja</span></span>
<span id="cb11-7"><a href="eda.html#cb11-7" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb11-8"><a href="eda.html#cb11-8" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb11-9"><a href="eda.html#cb11-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-10"><a href="eda.html#cb11-10" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;#d95f02&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb11-11"><a href="eda.html#cb11-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-12"><a href="eda.html#cb11-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del contenido de Ceniza Volante&quot;</span>,</span>
<span id="cb11-13"><a href="eda.html#cb11-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Ceniza Volante (kg/m³)&quot;</span>,</span>
<span id="cb11-14"><a href="eda.html#cb11-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span></span>
<span id="cb11-15"><a href="eda.html#cb11-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-16"><a href="eda.html#cb11-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-5-1.png" alt="" width="672" style="display: block; margin: auto;" />
La distribución es fuertemente bimodal e inflada en ceros. Presenta una concentración masiva en los <span class="math inline">\(0\text{ kg/m}^3\)</span> correspondiente a las mezclas tradicionales de control (<span class="math inline">\(55\%\)</span> de la muestra), seguida de un segundo agrupamiento entre los <span class="math inline">\(80\)</span> y <span class="math inline">\(160\text{ kg/m}^3\)</span> en aquellas formulaciones donde sí se sustituyó cemento por ceniza. Esta notable asimetría y falta de continuidad confirma la <strong>no normalidad</strong> de la variabl.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="eda.html#cb12-1" tabindex="-1"></a>df_clean <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="eda.html#cb12-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> edad)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="eda.html#cb12-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb12-4"><a href="eda.html#cb12-4" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb12-5"><a href="eda.html#cb12-5" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="dv">14</span>,           <span class="co"># Intervalos de 14 días (2 semanas)</span></span>
<span id="cb12-6"><a href="eda.html#cb12-6" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;#7570b3&quot;</span>,        <span class="co"># Tono violeta</span></span>
<span id="cb12-7"><a href="eda.html#cb12-7" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb12-8"><a href="eda.html#cb12-8" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb12-9"><a href="eda.html#cb12-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-10"><a href="eda.html#cb12-10" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;#7570b3&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb12-11"><a href="eda.html#cb12-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-12"><a href="eda.html#cb12-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Tiempo de Curado&quot;</span>,</span>
<span id="cb12-13"><a href="eda.html#cb12-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Tiempo de Curado (Días)&quot;</span>,</span>
<span id="cb12-14"><a href="eda.html#cb12-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span></span>
<span id="cb12-15"><a href="eda.html#cb12-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-16"><a href="eda.html#cb12-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-6-1.png" alt="" width="672" style="display: block; margin: auto;" />
La distribución exhibe un marcado sesgo positivo con picos, concentrando la gran mayoría de las observaciones en los <span class="math inline">\(28\text{ días}\)</span> la cual es la edad estándar de diseño y en periodos tempranos (<span class="math inline">\(\le 7\text{ días}\)</span>). La densidad decae drásticamente a partir de los <span class="math inline">\(56\text{ días}\)</span>, extendiéndose en una cola larga hasta los <span class="math inline">\(365\text{ días}\)</span>, lo cual evidencia una distribución <strong>no normal</strong> explicada por el diseño experimental enfocado en etapas normativas de obra.</p>
</div>
</div>
<div id="anlisis-univariado-de-las-variables" class="section level2 hasAnchor" number="3.8">
<h2><span class="header-section-number">3.8</span> Anlisis Univariado de las variables<a href="eda.html#anlisis-univariado-de-las-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="eda.html#cb13-1" tabindex="-1"></a><span class="co"># 1. Boxplot de Ceniza Volante</span></span>
<span id="cb13-2"><a href="eda.html#cb13-2" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="eda.html#cb13-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Fly Ash (component 3)(kg in a m^3 mixture)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="eda.html#cb13-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#d62728&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="eda.html#cb13-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-6"><a href="eda.html#cb13-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Ceniza Volante (Fly Ash)&quot;</span>,</span>
<span id="cb13-7"><a href="eda.html#cb13-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Ceniza Volante (kg/m³)&quot;</span>,</span>
<span id="cb13-8"><a href="eda.html#cb13-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb13-9"><a href="eda.html#cb13-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-10"><a href="eda.html#cb13-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb13-11"><a href="eda.html#cb13-11" tabindex="-1"></a></span>
<span id="cb13-12"><a href="eda.html#cb13-12" tabindex="-1"></a></span>
<span id="cb13-13"><a href="eda.html#cb13-13" tabindex="-1"></a><span class="co"># 2. Boxplot de Edad de Curado</span></span>
<span id="cb13-14"><a href="eda.html#cb13-14" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb13-15"><a href="eda.html#cb13-15" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Age (day)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb13-16"><a href="eda.html#cb13-16" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#e377c2&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb13-17"><a href="eda.html#cb13-17" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-18"><a href="eda.html#cb13-18" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Tiempo de Curado&quot;</span>,</span>
<span id="cb13-19"><a href="eda.html#cb13-19" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Edad (Días)&quot;</span>,</span>
<span id="cb13-20"><a href="eda.html#cb13-20" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb13-21"><a href="eda.html#cb13-21" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-22"><a href="eda.html#cb13-22" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb13-23"><a href="eda.html#cb13-23" tabindex="-1"></a></span>
<span id="cb13-24"><a href="eda.html#cb13-24" tabindex="-1"></a><span class="co"># 3. Boxplot de Resistencia a la Compresión (Target / Variable Respuesta)</span></span>
<span id="cb13-25"><a href="eda.html#cb13-25" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb13-26"><a href="eda.html#cb13-26" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Concrete compressive strength(MPa, megapascals)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb13-27"><a href="eda.html#cb13-27" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#bcbd22&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb13-28"><a href="eda.html#cb13-28" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-29"><a href="eda.html#cb13-29" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Resistencia a la Compresión&quot;</span>,</span>
<span id="cb13-30"><a href="eda.html#cb13-30" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Resistencia (MPa)&quot;</span>,</span>
<span id="cb13-31"><a href="eda.html#cb13-31" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb13-32"><a href="eda.html#cb13-32" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-33"><a href="eda.html#cb13-33" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="eda.html#cb14-1" tabindex="-1"></a>p1 </span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-7-1.png" alt="" width="672" style="display: block; margin: auto;" />
### Analisis boxplot Fly Ash</p>
<p>Se observa una distribución atipica con alta dispersión de los datos, además por la tabla anterior la media del uso de ceniza en las mezclas es <span class="math inline">\(54.2 kg/m^3\)</span> y una desviación estándar de <span class="math inline">\(64 kg/m^3\)</span></p>
<p>Sin embargo el diagrama de caja muestra que el 50% de los valores de ceniza coincide con el limite inferior, esto indica que el 50% de las mezclas no contienen contienen ceniza volante. Por otra parte, el 75% de las observaciones contienen una cantidad de ceniza menor o igual a <span class="math inline">\(118.6 kg/m^3\)</span>, mientras que el migote señala mezclas con un maximo de <span class="math inline">\(201.1 kg/m^3\)</span>, no se evidencia ningun valor atipico.</p>
<p>¿porque hay este comportamiento de los datos centrado en cero?
esto se debe a que el conjunto de datos contiene mezclas de control convencionales elaboradas exclusivamente con cemento tradicional para servir de base comparativa. Por ende, la ceniza volante actúa como un componente opcional.</p>
<div id="analisis-boxplot-tiempo-de-curado" class="section level3 hasAnchor" number="3.8.1">
<h3><span class="header-section-number">3.8.1</span> Analisis boxplot tiempo de curado<a href="eda.html#analisis-boxplot-tiempo-de-curado" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="eda.html#cb15-1" tabindex="-1"></a>p2</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-8-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>La variable <span class="math inline">\(\text{Age}\)</span> (días de curado) presenta una concentración en edades tempranas y unagran dispersión, reflejada en un tiempo promedio de curado de <span class="math inline">\(45.7\text{ días}\)</span> y una desviación estándar de <span class="math inline">\(63.2\text{ días}\)</span>.</p>
<p>El boxplot nos permite observar una distribución sesgada a la derecha, tambien el <span class="math inline">\(50\%\)</span> de las muestras fueron ensayadas a los <span class="math inline">\(28\text{ días}\)</span> o menos, el <span class="math inline">\(25\%\)</span> inferior corresponde a edades tempranas iguales o menores a <span class="math inline">\(7\text{ días}\)</span>, y el <span class="math inline">\(75\%\)</span> central se concentra por debajo de los <span class="math inline">\(56\text{ días}\)</span>. No obstante, el diagrama de caja evidencia una serie de <strong>valores extremos</strong> en la parte superior, con esayos a los <span class="math inline">\(90\)</span>, <span class="math inline">\(180\)</span>, <span class="math inline">\(270\)</span> y hasta un máximo de <span class="math inline">\(365\text{ días}\)</span> es decir un año completo de curado.</p>
<p><strong>¿Por qué existen valores atípicos tan elevados?</strong><br />
En la práctica de la ingeniería civil, los ensayos estándar de control de calidad se realizan de forma rutinaria a los <span class="math inline">\(7\)</span>, <span class="math inline">\(14\)</span> y principalmente a los <span class="math inline">\(28\text{ días}\)</span>. Los tiempos de curado prolongados (<span class="math inline">\(&gt; 90\text{ días}\)</span>) son ensayos de investigación concebidos para evaluar la durabilidad a largo plazo y la reacción tardía de adiciones minerales como la ceniza volante.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="eda.html#cb16-1" tabindex="-1"></a>p3</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-9-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>Para la variable objetivo “resistencia”, se observa un comportamiento mucho más homogéneo y balanceado, con un promedio de resistencia de <span class="math inline">\(35.8\text{ MPa}\)</span> y una desviación estándar de <span class="math inline">\(16.7\text{ MPa}\)</span>.</p>
<p>El 50% de los datos tienen una resistencia menor o igual a <span class="math inline">\(34.5\text{ MPa}\)</span>, mostrando una <strong>notable cercanía con el promedio de resistencia de las mezclas de concreto (<span class="math inline">\(35.8\text{ MPa}\)</span>)</strong>. En cuanto al rango intercuartílico, el <span class="math inline">\(25\%\)</span> de las mezclas con menor resistencia registran valores iguales o inferiores a <span class="math inline">\(23.7\text{ MPa}\)</span>, mientras que el <span class="math inline">\(75\%\)</span> de las muestras se sitúan por debajo de los <span class="math inline">\(46.1\text{ MPa}\)</span>. Los bigotes abarcan un rango que va desde un mínimo de <span class="math inline">\(2.3\text{ MPa}\)</span> (concreto de muy baja resistencia) hasta aproximadamente los <span class="math inline">\(80.0\text{ MPa}\)</span>. Se aprecian únicamente unos pocos <strong>valores atípicos superiores</strong> que alcanzan un máximo de <span class="math inline">\(82.6\text{ MPa}\)</span>.</p>
</div>
</div>
<div id="analisis-bivariado" class="section level2 hasAnchor" number="3.9">
<h2><span class="header-section-number">3.9</span> Analisis Bivariado<a href="eda.html#analisis-bivariado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="eda.html#cb17-1" tabindex="-1"></a>df_clean <span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="eda.html#cb17-2" tabindex="-1"></a>  <span class="fu">ggpairs</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-10-1.png" alt="" width="1248" style="display: block; margin: auto;" /></p>
<div id="creacion-de-nuevas-variables" class="section level3 hasAnchor" number="3.9.1">
<h3><span class="header-section-number">3.9.1</span> Creacion de nuevas variables<a href="eda.html#creacion-de-nuevas-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="eda.html#cb18-1" tabindex="-1"></a>df_fe <span class="ot">&lt;-</span> df_clean <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="eda.html#cb18-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-3"><a href="eda.html#cb18-3" tabindex="-1"></a>    <span class="co"># 1. Razón Agua / Cementante (Agua / [Cemento + Ceniza])</span></span>
<span id="cb18-4"><a href="eda.html#cb18-4" tabindex="-1"></a>    <span class="at">razon_agua_cementante =</span> agua <span class="sc">/</span> (cemento <span class="sc">+</span> ceniza),</span>
<span id="cb18-5"><a href="eda.html#cb18-5" tabindex="-1"></a>    </span>
<span id="cb18-6"><a href="eda.html#cb18-6" tabindex="-1"></a>    <span class="co"># 2. Porcentaje de Cemento sustituido por Ceniza (0% a ~50%)</span></span>
<span id="cb18-7"><a href="eda.html#cb18-7" tabindex="-1"></a>    <span class="at">pct_ceniza =</span> (ceniza <span class="sc">/</span> (cemento <span class="sc">+</span> ceniza)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb18-8"><a href="eda.html#cb18-8" tabindex="-1"></a>    </span>
<span id="cb18-9"><a href="eda.html#cb18-9" tabindex="-1"></a>    <span class="co"># 3. Clasificación del reemplazo en niveles (para futuros ANOVAs)</span></span>
<span id="cb18-10"><a href="eda.html#cb18-10" tabindex="-1"></a>    <span class="at">nivel_ceniza =</span> <span class="fu">factor</span>(<span class="fu">case_when</span>(</span>
<span id="cb18-11"><a href="eda.html#cb18-11" tabindex="-1"></a>      pct_ceniza <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">&quot;0% (Control)&quot;</span>,</span>
<span id="cb18-12"><a href="eda.html#cb18-12" tabindex="-1"></a>      pct_ceniza <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> pct_ceniza <span class="sc">&lt;=</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">&quot;Bajo (&lt;= 20%)&quot;</span>,</span>
<span id="cb18-13"><a href="eda.html#cb18-13" tabindex="-1"></a>      pct_ceniza <span class="sc">&gt;</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">&quot;Alto (&gt; 20%)&quot;</span></span>
<span id="cb18-14"><a href="eda.html#cb18-14" tabindex="-1"></a>    ), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;0% (Control)&quot;</span>, <span class="st">&quot;Bajo (&lt;= 20%)&quot;</span>, <span class="st">&quot;Alto (&gt; 20%)&quot;</span>)),</span>
<span id="cb18-15"><a href="eda.html#cb18-15" tabindex="-1"></a>    </span>
<span id="cb18-16"><a href="eda.html#cb18-16" tabindex="-1"></a>    <span class="co"># 4. Transformación Logarítmica de la Edad (Linealiza la ganancia de resistencia)</span></span>
<span id="cb18-17"><a href="eda.html#cb18-17" tabindex="-1"></a>    <span class="at">log_edad =</span> <span class="fu">log</span>(edad),</span>
<span id="cb18-18"><a href="eda.html#cb18-18" tabindex="-1"></a>    </span>
<span id="cb18-19"><a href="eda.html#cb18-19" tabindex="-1"></a>    <span class="co"># 5. Etapas estándar de curado</span></span>
<span id="cb18-20"><a href="eda.html#cb18-20" tabindex="-1"></a>    <span class="at">etapa_curado =</span> <span class="fu">factor</span>(<span class="fu">case_when</span>(</span>
<span id="cb18-21"><a href="eda.html#cb18-21" tabindex="-1"></a>      edad <span class="sc">&lt;=</span> <span class="dv">7</span> <span class="sc">~</span> <span class="st">&quot;Temprano (&lt;= 7d)&quot;</span>,</span>
<span id="cb18-22"><a href="eda.html#cb18-22" tabindex="-1"></a>      edad <span class="sc">&gt;</span> <span class="dv">7</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">28</span> <span class="sc">~</span> <span class="st">&quot;Estándar (14-28d)&quot;</span>,</span>
<span id="cb18-23"><a href="eda.html#cb18-23" tabindex="-1"></a>      edad <span class="sc">&gt;</span> <span class="dv">28</span> <span class="sc">~</span> <span class="st">&quot;Tardío (&gt; 28d)&quot;</span></span>
<span id="cb18-24"><a href="eda.html#cb18-24" tabindex="-1"></a>    ), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Temprano (&lt;= 7d)&quot;</span>, <span class="st">&quot;Estándar (14-28d)&quot;</span>, <span class="st">&quot;Tardío (&gt; 28d)&quot;</span>))</span>
<span id="cb18-25"><a href="eda.html#cb18-25" tabindex="-1"></a>  )</span></code></pre></div>
</div>
<div id="tabla-descriptiva-de-las-nuevas-variables" class="section level3 hasAnchor" number="3.9.2">
<h3><span class="header-section-number">3.9.2</span> Tabla descriptiva de las nuevas variables<a href="eda.html#tabla-descriptiva-de-las-nuevas-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="eda.html#cb19-1" tabindex="-1"></a>tabla_nuevas_numericas <span class="ot">&lt;-</span> df_fe <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="eda.html#cb19-2" tabindex="-1"></a>  <span class="fu">select</span>(razon_agua_cementante, pct_ceniza, log_edad) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="eda.html#cb19-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb19-4"><a href="eda.html#cb19-4" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb19-5"><a href="eda.html#cb19-5" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>,</span>
<span id="cb19-6"><a href="eda.html#cb19-6" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb19-7"><a href="eda.html#cb19-7" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb19-8"><a href="eda.html#cb19-8" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">|&gt;</span></span>
<span id="cb19-9"><a href="eda.html#cb19-9" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb19-10"><a href="eda.html#cb19-10" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(valor)),</span>
<span id="cb19-11"><a href="eda.html#cb19-11" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-12"><a href="eda.html#cb19-12" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-13"><a href="eda.html#cb19-13" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-14"><a href="eda.html#cb19-14" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-15"><a href="eda.html#cb19-15" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-16"><a href="eda.html#cb19-16" tabindex="-1"></a>    <span class="at">asim =</span> <span class="fu">skewness</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-17"><a href="eda.html#cb19-17" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-18"><a href="eda.html#cb19-18" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb19-19"><a href="eda.html#cb19-19" tabindex="-1"></a>  )</span>
<span id="cb19-20"><a href="eda.html#cb19-20" tabindex="-1"></a></span>
<span id="cb19-21"><a href="eda.html#cb19-21" tabindex="-1"></a>tabla_nuevas_numericas <span class="sc">|&gt;</span></span>
<span id="cb19-22"><a href="eda.html#cb19-22" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb19-23"><a href="eda.html#cb19-23" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Estadisticas descriptivas de las nuevas variables numericas&quot;</span>,</span>
<span id="cb19-24"><a href="eda.html#cb19-24" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb19-25"><a href="eda.html#cb19-25" tabindex="-1"></a>    <span class="at">format =</span> <span class="fu">ifelse</span>(knitr<span class="sc">::</span><span class="fu">is_latex_output</span>(), <span class="st">&quot;latex&quot;</span>, <span class="st">&quot;html&quot;</span>)</span>
<span id="cb19-26"><a href="eda.html#cb19-26" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb19-27"><a href="eda.html#cb19-27" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb19-28"><a href="eda.html#cb19-28" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb19-29"><a href="eda.html#cb19-29" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hold_position&quot;</span>, <span class="st">&quot;scale_down&quot;</span>),</span>
<span id="cb19-30"><a href="eda.html#cb19-30" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb19-31"><a href="eda.html#cb19-31" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb19-32"><a href="eda.html#cb19-32" tabindex="-1"></a>  )</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabla-nuevas-variables-numericas">Table 3.5: </span>Estadisticas descriptivas de las nuevas variables numericas
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
mediana
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
asim
</th>
<th style="text-align:right;">
curtosis
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
log_edad
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
3.165
</td>
<td style="text-align:right;">
1.191
</td>
<td style="text-align:right;">
3.332
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
5.900
</td>
<td style="text-align:right;">
-0.151
</td>
<td style="text-align:right;">
2.642
</td>
</tr>
<tr>
<td style="text-align:left;">
pct_ceniza
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
15.526
</td>
<td style="text-align:right;">
18.788
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
58.841
</td>
<td style="text-align:right;">
0.649
</td>
<td style="text-align:right;">
1.859
</td>
</tr>
<tr>
<td style="text-align:left;">
razon_agua_cementante
</td>
<td style="text-align:right;">
1030
</td>
<td style="text-align:right;">
0.612
</td>
<td style="text-align:right;">
0.278
</td>
<td style="text-align:right;">
0.548
</td>
<td style="text-align:right;">
0.266
</td>
<td style="text-align:right;">
1.882
</td>
<td style="text-align:right;">
1.965
</td>
<td style="text-align:right;">
7.529
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="eda.html#cb20-1" tabindex="-1"></a>tabla_nuevas_categoricas <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb20-2"><a href="eda.html#cb20-2" tabindex="-1"></a>  df_fe <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="eda.html#cb20-3" tabindex="-1"></a>    <span class="fu">count</span>(nivel_ceniza, <span class="at">name =</span> <span class="st">&quot;frecuencia&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="eda.html#cb20-4" tabindex="-1"></a>    <span class="fu">transmute</span>(<span class="at">variable =</span> <span class="st">&quot;nivel_ceniza&quot;</span>, <span class="at">categoria =</span> <span class="fu">as.character</span>(nivel_ceniza), frecuencia),</span>
<span id="cb20-5"><a href="eda.html#cb20-5" tabindex="-1"></a>  df_fe <span class="sc">|&gt;</span></span>
<span id="cb20-6"><a href="eda.html#cb20-6" tabindex="-1"></a>    <span class="fu">count</span>(etapa_curado, <span class="at">name =</span> <span class="st">&quot;frecuencia&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-7"><a href="eda.html#cb20-7" tabindex="-1"></a>    <span class="fu">transmute</span>(<span class="at">variable =</span> <span class="st">&quot;etapa_curado&quot;</span>, <span class="at">categoria =</span> <span class="fu">as.character</span>(etapa_curado), frecuencia)</span>
<span id="cb20-8"><a href="eda.html#cb20-8" tabindex="-1"></a>)</span>
<span id="cb20-9"><a href="eda.html#cb20-9" tabindex="-1"></a></span>
<span id="cb20-10"><a href="eda.html#cb20-10" tabindex="-1"></a>tabla_nuevas_categoricas <span class="sc">|&gt;</span></span>
<span id="cb20-11"><a href="eda.html#cb20-11" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb20-12"><a href="eda.html#cb20-12" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Frecuencias de las nuevas variables categoricas&quot;</span>,</span>
<span id="cb20-13"><a href="eda.html#cb20-13" tabindex="-1"></a>    <span class="at">format =</span> <span class="fu">ifelse</span>(knitr<span class="sc">::</span><span class="fu">is_latex_output</span>(), <span class="st">&quot;latex&quot;</span>, <span class="st">&quot;html&quot;</span>)</span>
<span id="cb20-14"><a href="eda.html#cb20-14" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb20-15"><a href="eda.html#cb20-15" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb20-16"><a href="eda.html#cb20-16" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>),</span>
<span id="cb20-17"><a href="eda.html#cb20-17" tabindex="-1"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hold_position&quot;</span>),</span>
<span id="cb20-18"><a href="eda.html#cb20-18" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb20-19"><a href="eda.html#cb20-19" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb20-20"><a href="eda.html#cb20-20" tabindex="-1"></a>  )</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabla-nuevas-variables-categoricas">Table 3.6: </span>Frecuencias de las nuevas variables categoricas
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:left;">
categoria
</th>
<th style="text-align:right;">
frecuencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
nivel_ceniza
</td>
<td style="text-align:left;">
0% (Control)
</td>
<td style="text-align:right;">
566
</td>
</tr>
<tr>
<td style="text-align:left;">
nivel_ceniza
</td>
<td style="text-align:left;">
Bajo (&lt;= 20%)
</td>
<td style="text-align:right;">
43
</td>
</tr>
<tr>
<td style="text-align:left;">
nivel_ceniza
</td>
<td style="text-align:left;">
Alto (&gt; 20%)
</td>
<td style="text-align:right;">
421
</td>
</tr>
<tr>
<td style="text-align:left;">
etapa_curado
</td>
<td style="text-align:left;">
Temprano (&lt;= 7d)
</td>
<td style="text-align:right;">
262
</td>
</tr>
<tr>
<td style="text-align:left;">
etapa_curado
</td>
<td style="text-align:left;">
Estándar (14-28d)
</td>
<td style="text-align:right;">
487
</td>
</tr>
<tr>
<td style="text-align:left;">
etapa_curado
</td>
<td style="text-align:left;">
Tardío (&gt; 28d)
</td>
<td style="text-align:right;">
281
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="pruebas-de-normalidad" class="section level2 hasAnchor" number="3.10">
<h2><span class="header-section-number">3.10</span> Pruebas de normalidad<a href="eda.html#pruebas-de-normalidad" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="eda.html#cb21-1" tabindex="-1"></a><span class="co"># --- 1. PRUEBAS ESTADÍSTICAS DE NORMALIDAD ---</span></span>
<span id="cb21-2"><a href="eda.html#cb21-2" tabindex="-1"></a></span>
<span id="cb21-3"><a href="eda.html#cb21-3" tabindex="-1"></a><span class="co"># Prueba de Shapiro-Wilk para la variable de respuesta</span></span>
<span id="cb21-4"><a href="eda.html#cb21-4" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>resistencia)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$resistencia
## W = 0.97979, p-value = 0.00000000009023</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="eda.html#cb23-1" tabindex="-1"></a><span class="co"># Prueba de Shapiro-Wilk para las variables independientes</span></span>
<span id="cb23-2"><a href="eda.html#cb23-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>ceniza)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$ceniza
## W = 0.76201, p-value &lt; 0.00000000000000022</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="eda.html#cb25-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>edad)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$edad
## W = 0.59071, p-value &lt; 0.00000000000000022</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="eda.html#cb27-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>cemento)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$cemento
## W = 0.95896, p-value &lt; 0.00000000000000022</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="eda.html#cb29-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>agua)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$agua
## W = 0.9804, p-value = 0.0000000001473</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="eda.html#cb31-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>agregado_grueso)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$agregado_grueso
## W = 0.98245, p-value = 0.0000000008346</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="eda.html#cb33-1" tabindex="-1"></a><span class="fu">lapply</span>(df_clean, shapiro.test)</span></code></pre></div>
<pre><code>## $cemento
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.95896, p-value &lt; 0.00000000000000022
## 
## 
## $escoria
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.81241, p-value &lt; 0.00000000000000022
## 
## 
## $ceniza
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.76201, p-value &lt; 0.00000000000000022
## 
## 
## $agua
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.9804, p-value = 0.0000000001473
## 
## 
## $superplast
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.86605, p-value &lt; 0.00000000000000022
## 
## 
## $agregado_grueso
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.98245, p-value = 0.0000000008346
## 
## 
## $agregado_fino
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.98067, p-value = 0.0000000001843
## 
## 
## $edad
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.59071, p-value &lt; 0.00000000000000022
## 
## 
## $resistencia
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.97979, p-value = 0.00000000009023</code></pre>
<div id="validación-visual-q-q-plots" class="section level3 hasAnchor" number="3.10.1">
<h3><span class="header-section-number">3.10.1</span> 2. VALIDACIÓN VISUAL (Q-Q PLOTS)<a href="eda.html#validaci%C3%B3n-visual-q-q-plots" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="eda.html#cb35-1" tabindex="-1"></a><span class="co"># Gráfico para la Resistencia</span></span>
<span id="cb35-2"><a href="eda.html#cb35-2" tabindex="-1"></a><span class="fu">qqnorm</span>(df_clean<span class="sc">$</span>resistencia, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>, </span>
<span id="cb35-3"><a href="eda.html#cb35-3" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;Gráfico Q-Q: Resistencia a la Compresión&quot;</span>)</span>
<span id="cb35-4"><a href="eda.html#cb35-4" tabindex="-1"></a><span class="fu">qqline</span>(df_clean<span class="sc">$</span>resistencia, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-13-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="eda.html#cb36-1" tabindex="-1"></a><span class="co"># Gráfico para la Edad</span></span>
<span id="cb36-2"><a href="eda.html#cb36-2" tabindex="-1"></a><span class="fu">qqnorm</span>(df_clean<span class="sc">$</span>edad, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>, </span>
<span id="cb36-3"><a href="eda.html#cb36-3" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;Gráfico Q-Q: Tiempo de Curado (Edad)&quot;</span>)</span>
<span id="cb36-4"><a href="eda.html#cb36-4" tabindex="-1"></a><span class="fu">qqline</span>(df_clean<span class="sc">$</span>edad, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-13-2.png" alt="" width="672" style="display: block; margin: auto;" />
1. Interpretación del Gráfico Q-Q para la Resistencia a la Compresión</p>
<p>Comportamiento central: En el centro del gráfico, la gran mayoría de los puntos se alinean bastante bien sobre la línea diagonal roja. Esto indica que los valores medios de resistencia (alrededor de los 35 MPa) tienen un comportamiento muy cercano a una distribución simétrica normal.</p>
<p>Desviación en los extremos (Colas): El gráfico seguramente muestra que los puntos se separan ligeramente de la línea roja en el extremo inferior (esquina inferior izquierda) y en el extremo superior (esquina superior derecha).</p>
<p>Conclusión: Esta pequeña desviación en los extremos es típica de variables que están acotadas (la resistencia no puede ser negativa) o que tienen unos pocos valores atípicamente altos (mezclas de muy alto rendimiento). Esto concuerda con tu prueba de Shapiro-Wilk (<span class="math inline">\(W = 0.97979\)</span>), donde la variable se ve “casi” normal en el centro, pero las ligeras desviaciones en las colas hacen que la prueba estadística la rechace matemáticamente.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="eda.html#cb37-1" tabindex="-1"></a><span class="co"># Pruebas estadísticas (Shapiro-Wilk)</span></span>
<span id="cb37-2"><a href="eda.html#cb37-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>cemento)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$cemento
## W = 0.95896, p-value &lt; 0.00000000000000022</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="eda.html#cb39-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>agua)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$agua
## W = 0.9804, p-value = 0.0000000001473</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="eda.html#cb41-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(df_clean<span class="sc">$</span>agregado_grueso)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$agregado_grueso
## W = 0.98245, p-value = 0.0000000008346</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="eda.html#cb43-1" tabindex="-1"></a><span class="co"># (Puedes copiar y pegar para el resto de variables)</span></span>
<span id="cb43-2"><a href="eda.html#cb43-2" tabindex="-1"></a></span>
<span id="cb43-3"><a href="eda.html#cb43-3" tabindex="-1"></a><span class="co"># Aplicar Shapiro-Wilk a todas las columnas de df_clean de un solo golpe</span></span>
<span id="cb43-4"><a href="eda.html#cb43-4" tabindex="-1"></a>resultados_normalidad <span class="ot">&lt;-</span> <span class="fu">lapply</span>(df_clean, shapiro.test)</span>
<span id="cb43-5"><a href="eda.html#cb43-5" tabindex="-1"></a>resultados_normalidad</span></code></pre></div>
<pre><code>## $cemento
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.95896, p-value &lt; 0.00000000000000022
## 
## 
## $escoria
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.81241, p-value &lt; 0.00000000000000022
## 
## 
## $ceniza
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.76201, p-value &lt; 0.00000000000000022
## 
## 
## $agua
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.9804, p-value = 0.0000000001473
## 
## 
## $superplast
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.86605, p-value &lt; 0.00000000000000022
## 
## 
## $agregado_grueso
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.98245, p-value = 0.0000000008346
## 
## 
## $agregado_fino
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.98067, p-value = 0.0000000001843
## 
## 
## $edad
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.59071, p-value &lt; 0.00000000000000022
## 
## 
## $resistencia
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.97979, p-value = 0.00000000009023</code></pre>
<p>Al evaluar las nueve variables del conjunto de datos mediante la prueba de normalidad de Shapiro-Wilk, se obtienen las siguientes conclusiones estadísticas para documentar en tu Análisis Exploratorio de Datos (EDA):</p>
<p>Rechazo generalizado de la normalidad: Todas las variables analizadas arrojaron un p-valor estrictamente inferior al nivel de significancia de <span class="math inline">\(0.05\)</span>. En consecuencia, se rechaza la hipótesis nula (<span class="math inline">\(H_0\)</span>) para todo el conjunto de datos y se concluye estadísticamente que ninguna variable sigue una distribución normal perfecta.</p>
<p>Variables con desviación severa (Alta asimetría o inflación de ceros): Las variables edad (<span class="math inline">\(W = 0.59071\)</span>), ceniza (<span class="math inline">\(W = 0.76201\)</span>), escoria (<span class="math inline">\(W = 0.81241\)</span>) y superplast (<span class="math inline">\(W = 0.86605\)</span>) presentan las violaciones más fuertes al supuesto de normalidad, reflejadas en los estadísticos <span class="math inline">\(W\)</span> más bajos y p-valores menores a <span class="math inline">\(0.00000000000000022\)</span>. Esto corrobora el análisis gráfico preliminar: la edad tiene saltos marcados por los tiempos estándar de curado, mientras que los aditivos presentan una enorme concentración de ceros (mezclas que no los incluyen).</p>
<p>Variables con aproximación a la normalidad (Sensibilidad de la prueba): Las variables agregado_grueso (<span class="math inline">\(W = 0.98245\)</span>), agregado_fino (<span class="math inline">\(W = 0.98067\)</span>), agua (<span class="math inline">\(W = 0.9804\)</span>), resistencia (<span class="math inline">\(W = 0.97979\)</span>) y cemento (<span class="math inline">\(W = 0.95896\)</span>) poseen un estadístico <span class="math inline">\(W\)</span> muy cercano a <span class="math inline">\(1\)</span>. Aunque sus p-valores obligan a rechazar la normalidad teórica (fluctuando en el orden de <span class="math inline">\(10^{-10}\)</span> a <span class="math inline">\(10^{-12}\)</span>), la estructura de sus datos es razonablemente simétrica y acampanada. El rechazo se explica principalmente por la hipersensibilidad de la prueba de Shapiro-Wilk ante tamaños de muestra grandes (<span class="math inline">\(N=1030\)</span>), donde cualquier desviación milimétrica de la campana de Gauss resulta estadísticamente significativa.</p>
<p>Impacto metodológico para el modelo: Dado que las variables no son normales por naturaleza, no se recomienda utilizar correlaciones paramétricas simples (como Pearson) para medir sus relaciones, sino alternativas robustas como la correlación de Spearman. Además, la regresión múltiple exigirá validar la normalidad directamente sobre los residuos predictivos y no sobre estas variables independientes aisladas, contemplando posibles transformaciones logarítmicas para las variables del primer grupo (edad y aditivos).</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="eda.html#cb45-1" tabindex="-1"></a><span class="co"># Gráficos Q-Q para ver visualmente la distribución</span></span>
<span id="cb45-2"><a href="eda.html#cb45-2" tabindex="-1"></a><span class="fu">qqnorm</span>(df_clean<span class="sc">$</span>agua, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>, <span class="at">main =</span> <span class="st">&quot;Gráfico Q-Q: Cantidad de Agua&quot;</span>)</span>
<span id="cb45-3"><a href="eda.html#cb45-3" tabindex="-1"></a><span class="fu">qqline</span>(df_clean<span class="sc">$</span>agua, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-15-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="eda.html#cb46-1" tabindex="-1"></a><span class="fu">qqnorm</span>(df_clean<span class="sc">$</span>cemento, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>, <span class="at">main =</span> <span class="st">&quot;Gráfico Q-Q: Cemento&quot;</span>)</span>
<span id="cb46-2"><a href="eda.html#cb46-2" tabindex="-1"></a><span class="fu">qqline</span>(df_clean<span class="sc">$</span>cemento, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-15-2.png" alt="" width="672" style="display: block; margin: auto;" />
2. Interpretación del Gráfico Q-Q para el Tiempo de Curado (Edad)</p>
<p>Falta de alineación y forma de “escalera”: Al mirar este gráfico, los puntos no siguen una línea recta continua. En su lugar, vas a ver agrupaciones densas de puntos dispuestas de forma horizontal (como si fueran escalones) y muy separadas de la línea roja de referencia.</p>
<p>Por qué ocurre esto (Asimetría severa): Esta desviación extrema ocurre porque el tiempo de curado no es una variable continua natural en este experimento. Los laboratoristas toman medidas en días fijos normativos (3, 7, 14, 28, 56 días, etc.), creando “saltos” en la distribución. Además, como la enorme mayoría de las pruebas se hacen a los 28 días y muy pocas llegan a un año (365 días), la distribución tiene un sesgo altísimo hacia la izquierda.</p>
<p>Conclusión: La trayectoria de los puntos corrobora visualmente el pésimo resultado de su prueba de Shapiro-Wilk (<span class="math inline">\(W = 0.59071\)</span>). La edad presenta una desviación radical respecto al modelo de campana de Gauss, confirmando una distribución discreta, marcadamente sesgada hacia la derecha (valores tempranos) y con una cola larga.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["Proyecto_Final_Metodos_Estadisticos.pdf", "Proyecto_Final_Metodos_Estadisticos.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
