% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{book}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage[]{natbib}
\bibliographystyle{apalike}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabularx}
\usepackage{xltabular}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Análisis estadístico del efecto de la ceniza volante sobre la resistencia del concreto},
  pdfauthor={Camilo Padilla \& Juan Campo},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Análisis estadístico del efecto de la ceniza volante sobre la resistencia del concreto}
\author{Camilo Padilla \& Juan Campo}
\date{2026-10-06}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\chapter{Presentación}\label{presentaciuxf3n}

Este proyecto presenta un análisis estadístico de la resistencia a la compresión del concreto a partir del conjunto de datos \textbf{Concrete Compressive Strength}, compuesto por 1.030 mezclas experimentales.

El estudio examina la relación entre la incorporación de ceniza volante, el tiempo de curado y la resistencia alcanzada por el concreto. Para ello, se aplican técnicas de análisis exploratorio, pruebas de hipótesis, comparación de grupos, análisis de correlación y modelación estadística, con el propósito de evaluar el comportamiento del material y la viabilidad del uso de la ceniza volante como sustituto parcial del cemento.

\section{Estructura del Documento}\label{estructura-del-documento}

\begin{itemize}
\tightlist
\item
  \textbf{Capítulo 1}: Introducción y Objetivos del Estudio.
\item
  \textbf{Capítulo 2}: Análisis Exploratorio de Datos (EDA).
\item
  \textbf{Capítulos siguientes}: Modelación y Conclusiones.
\end{itemize}

\chapter{Introducción y Objetivos}\label{intro}

\section{Contexto}\label{contexto}

En la ingeniería civil y los materiales de construcción, la resistencia a la compresión del concreto es una propiedad fundamental que determina la calidad y seguridad de las estructuras. Su propiedad mecánica más crítica es la resistencia a la compresión, ya que determina la capacidad de carga que tiene el material y una estructura de sopartar sin colapasar. De forma tradicional, la verificación de resistencia necesita un periodo estándar de 28 días de curado, es decir el proceso de control de la humedad y la temperatura para garantizar que el cemento mantenga la hidratación adecuada durante sus primeras etapas de endurecimiento.

\section{Problemática}\label{problemuxe1tica}

En la industria de la construcción y la ingeniería civil, la resistencia de la compresión de concreto es la propiedad mecánica que garantiza la seguridad de millones de estructuras en el mundo. La sustitución parcial de cemento por ceniza volante tambien conocido como ``fly ash'' es una alternativa económica y sostenible en la construcción; sin embargo, al ser un material de reacción lenta, existe incertidumbre sobre si compromete la resistencia del concreto en edades tempranas (1 a 7 días) o si la incrementa con un mayor tiempo de curado (28 a 90+ días).

Por tanto, el problema central radica en determinar estadísticamente: ¿En qué medida el uso de ceniza volante y el tiempo de curado influyen en la resistencia a la compresión del concreto a lo largo de sus distintas etapas de maduración?

\section{Objetivos del Proyecto}\label{objetivos-del-proyecto}

\subsection{Objetivo general}\label{objetivo-general}

Evaluar el impacto de la incorporación de ceniza volante (Fly Ash) y del tiempo de curado sobre la resistencia a la compresión del concreto, mediante análisis inferencial y pruebas de hipótesis, para determinar la viabilidad técnica y el comportamiento mecánico de estas formulaciones.

\subsection{Objetivos especificos}\label{objetivos-especificos}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Estimar los intervalos de confianza y verificar los supuestos de normalidad para la resistencia del concreto y la dosificación de ceniza volante.
\item
  Comparar la resistencia media a la compresión entre mezclas con y sin ceniza volante, calculando el tamaño del efecto.
\end{enumerate}

3.Evaluar las diferencias de resistencia entre las etapas de curado (temprana, estándar y tardía) mediante análisis de varianza y pruebas post-hoc.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Determinar el grado de correlación entre la cantidad de ceniza volante dosificada y la resistencia alcanzada en el material.
\end{enumerate}

\section{Justificación}\label{justificaciuxf3n}

La ceniza volante es un residuo industrial considerablemente más barato que el cemento tradicional; validar su eficacia permite reducir los costos de fabricación de las mezclas sin comprometer la calidad.

\chapter{Análisis Exploratorio de Datos (EDA)}\label{eda}

En este capítulo analizamos las variables cuantitativas del dataset de Concrete Compressive Strength (Resistencia del Concreto).

\section{Dataset y ficha tecnica}\label{dataset-y-ficha-tecnica}

\begin{itemize}
\item
  \textbf{Fuente:} UCI Machine Learning Repository (Donado por el Prof.~I-Cheng Yeh, 2007).
\item
  \textbf{Área:} Ingeniería Civil / Ciencia de Materiales.
\item
  \textbf{Número de Observaciones (}N\textbf{):} 1,030 mezclas experimentales.
\item
  \textbf{Número de Variables:} 9 variables cuantitativas (8 independientes + 1 dependiente).
\item
  \textbf{Valores Faltantes:} Ninguno.
\end{itemize}

\section{Importamos librerias}\label{importamos-librerias}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse) }
\FunctionTok{library}\NormalTok{(moments) }
\FunctionTok{library}\NormalTok{(patchwork) }
\FunctionTok{library}\NormalTok{(GGally) }
\FunctionTok{library}\NormalTok{(dplyr) }
\FunctionTok{library}\NormalTok{(effsize) }
\FunctionTok{library}\NormalTok{(rstatix)}
\FunctionTok{library}\NormalTok{(lmtest)   }
\FunctionTok{library}\NormalTok{(car)      }
\FunctionTok{library}\NormalTok{(janitor)  }
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(kableExtra)}
\end{Highlighting}
\end{Shaded}

\section{Carga de Datos}\label{carga-de-datos}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}
\NormalTok{Concrete\_Data }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"concrete+compressive+strength/Concrete\_Data.xls"}\NormalTok{)}

\NormalTok{df}\OtherTok{\textless{}{-}}\NormalTok{ Concrete\_Data}
\end{Highlighting}
\end{Shaded}

\section{Diccionario de Variables}\label{diccionario-de-variables}

Aclaramos que cada observacion representa un ensayo de laboratorio con una receta individual con ingredientes mezclados para hacer un metro cubico de cemento, el tiempo que se dejo reposar y la fuerza que resistio.

Todas las variables son cuantitativas continuas:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diccionario\_variables }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{variable =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"Cemento"}\NormalTok{, }\StringTok{"Escoria de alto horno"}\NormalTok{, }\StringTok{"Ceniza volante"}\NormalTok{, }\StringTok{"Agua"}\NormalTok{,}
    \StringTok{"Superplastificante"}\NormalTok{, }\StringTok{"Agregado Grueso"}\NormalTok{, }\StringTok{"Agregado Fino"}\NormalTok{, }\StringTok{"Edad"}\NormalTok{, }\StringTok{"Resistencia"}
\NormalTok{  ),}
  \AttributeTok{nombre\_dataset =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"Cement"}\NormalTok{, }\StringTok{"Blast\_Furnace\_Slag"}\NormalTok{, }\StringTok{"Fly\_Ash"}\NormalTok{, }\StringTok{"Water"}\NormalTok{, }\StringTok{"Superplasticizer"}\NormalTok{,}
    \StringTok{"Coarse\_Aggregate"}\NormalTok{, }\StringTok{"Fine\_Aggregate"}\NormalTok{, }\StringTok{"Age"}\NormalTok{, }\StringTok{"Concrete\_Compressive\_Strength"}
\NormalTok{  ),}
  \AttributeTok{tipo =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{rep}\NormalTok{(}\StringTok{"Entrada (Indep.)"}\NormalTok{, }\DecValTok{8}\NormalTok{), }\StringTok{"Salida (Dependiente)"}
\NormalTok{  ),}
  \AttributeTok{unidad =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{rep}\NormalTok{(}\StringTok{"kg/m\^{}3"}\NormalTok{, }\DecValTok{7}\NormalTok{), }\StringTok{"Dias (1 a 365)"}\NormalTok{, }\StringTok{"MPa"}
\NormalTok{  ),}
  \AttributeTok{descripcion =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"Componente aglutinante principal."}\NormalTok{,}
    \StringTok{"Subproducto siderurgico que mejora durabilidad."}\NormalTok{,}
    \StringTok{"Subproducto de centrales termicas."}\NormalTok{,}
    \StringTok{"Cantidad de agua."}\NormalTok{,}
    \StringTok{"Aditivo quimico que reduce necesidad de agua."}\NormalTok{,}
    \StringTok{"Grava / Piedra chancada."}\NormalTok{,}
    \StringTok{"Arena."}\NormalTok{,}
    \StringTok{"Tiempo de maduracion/curado del concreto."}\NormalTok{,}
    \StringTok{"Resistencia final a la compresion."}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{diccionario\_variables }\SpecialCharTok{|\textgreater{}}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Diccionario de variables del conjunto de datos"}\NormalTok{,}
    \AttributeTok{format =} \FunctionTok{ifelse}\NormalTok{(knitr}\SpecialCharTok{::}\FunctionTok{is\_latex\_output}\NormalTok{(), }\StringTok{"latex"}\NormalTok{, }\StringTok{"html"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{, }\StringTok{"scale\_down"}\NormalTok{),}
    \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{\label{tab:tabla-diccionario}Diccionario de variables del conjunto de datos}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|l|l|l|l}
\hline
variable & nombre\_dataset & tipo & unidad & descripcion\\
\hline
\cellcolor{gray!10}{Cemento} & \cellcolor{gray!10}{Cement} & \cellcolor{gray!10}{Entrada (Indep.)} & \cellcolor{gray!10}{kg/m\textasciicircum{}3} & \cellcolor{gray!10}{Componente aglutinante principal.}\\
\hline
Escoria de alto horno & Blast\_Furnace\_Slag & Entrada (Indep.) & kg/m\textasciicircum{}3 & Subproducto siderurgico que mejora durabilidad.\\
\hline
\cellcolor{gray!10}{Ceniza volante} & \cellcolor{gray!10}{Fly\_Ash} & \cellcolor{gray!10}{Entrada (Indep.)} & \cellcolor{gray!10}{kg/m\textasciicircum{}3} & \cellcolor{gray!10}{Subproducto de centrales termicas.}\\
\hline
Agua & Water & Entrada (Indep.) & kg/m\textasciicircum{}3 & Cantidad de agua.\\
\hline
\cellcolor{gray!10}{Superplastificante} & \cellcolor{gray!10}{Superplasticizer} & \cellcolor{gray!10}{Entrada (Indep.)} & \cellcolor{gray!10}{kg/m\textasciicircum{}3} & \cellcolor{gray!10}{Aditivo quimico que reduce necesidad de agua.}\\
\hline
Agregado Grueso & Coarse\_Aggregate & Entrada (Indep.) & kg/m\textasciicircum{}3 & Grava / Piedra chancada.\\
\hline
\cellcolor{gray!10}{Agregado Fino} & \cellcolor{gray!10}{Fine\_Aggregate} & \cellcolor{gray!10}{Entrada (Indep.)} & \cellcolor{gray!10}{kg/m\textasciicircum{}3} & \cellcolor{gray!10}{Arena.}\\
\hline
Edad & Age & Entrada (Indep.) & Dias (1 a 365) & Tiempo de maduracion/curado del concreto.\\
\hline
\cellcolor{gray!10}{Resistencia} & \cellcolor{gray!10}{Concrete\_Compressive\_Strength} & \cellcolor{gray!10}{Salida (Dependiente)} & \cellcolor{gray!10}{MPa} & \cellcolor{gray!10}{Resistencia final a la compresion.}\\
\hline
\end{tabular}}
\end{table}

\section{Exploración del data set.}\label{exploraciuxf3n-del-data-set.}

Resumimos los nombres de las variables

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{cemento          =} \StringTok{\textasciigrave{}}\AttributeTok{Cement (component 1)(kg in a m\^{}3 mixture)}\StringTok{\textasciigrave{}}\NormalTok{,}
    \AttributeTok{escoria          =} \StringTok{\textasciigrave{}}\AttributeTok{Blast Furnace Slag (component 2)(kg in a m\^{}3 mixture)}\StringTok{\textasciigrave{}}\NormalTok{,}
    \AttributeTok{ceniza           =} \StringTok{\textasciigrave{}}\AttributeTok{Fly Ash (component 3)(kg in a m\^{}3 mixture)}\StringTok{\textasciigrave{}}\NormalTok{,}
    \AttributeTok{agua             =} \StringTok{\textasciigrave{}}\AttributeTok{Water  (component 4)(kg in a m\^{}3 mixture)}\StringTok{\textasciigrave{}}\NormalTok{,}
    \AttributeTok{superplast       =} \StringTok{\textasciigrave{}}\AttributeTok{Superplasticizer (component 5)(kg in a m\^{}3 mixture)}\StringTok{\textasciigrave{}}\NormalTok{,}
    \AttributeTok{agregado\_grueso  =} \StringTok{\textasciigrave{}}\AttributeTok{Coarse Aggregate  (component 6)(kg in a m\^{}3 mixture)}\StringTok{\textasciigrave{}}\NormalTok{,}
    \AttributeTok{agregado\_fino    =} \StringTok{\textasciigrave{}}\AttributeTok{Fine Aggregate (component 7)(kg in a m\^{}3 mixture)}\StringTok{\textasciigrave{}}\NormalTok{,}
    \AttributeTok{edad             =} \StringTok{\textasciigrave{}}\AttributeTok{Age (day)}\StringTok{\textasciigrave{}}\NormalTok{,}
    \AttributeTok{resistencia      =} \StringTok{\textasciigrave{}}\AttributeTok{Concrete compressive strength(MPa, megapascals)}\StringTok{\textasciigrave{}}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\section{Calidad y estructura de los datos}\label{calidad-y-estructura-de-los-datos}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{calidad\_datos }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{variable =} \FunctionTok{names}\NormalTok{(df\_clean),}
  \AttributeTok{clase =} \FunctionTok{map\_chr}\NormalTok{(df\_clean, }\SpecialCharTok{\textasciitilde{}} \FunctionTok{class}\NormalTok{(.x)[}\DecValTok{1}\NormalTok{]),}
  \AttributeTok{tipo =} \FunctionTok{map\_chr}\NormalTok{(df\_clean, typeof),}
  \AttributeTok{faltantes =} \FunctionTok{map\_int}\NormalTok{(df\_clean, }\SpecialCharTok{\textasciitilde{}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(.x))),}
  \AttributeTok{valores\_unicos =} \FunctionTok{map\_int}\NormalTok{(df\_clean, n\_distinct)}
\NormalTok{)}

\NormalTok{calidad\_datos }\SpecialCharTok{|\textgreater{}}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Calidad y estructura de los datos"}\NormalTok{,}
    \AttributeTok{digits =} \DecValTok{0}\NormalTok{,}
    \AttributeTok{format =} \FunctionTok{ifelse}\NormalTok{(knitr}\SpecialCharTok{::}\FunctionTok{is\_latex\_output}\NormalTok{(), }\StringTok{"latex"}\NormalTok{, }\StringTok{"html"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{),}
    \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{\label{tab:calidad-datos}Calidad y estructura de los datos}
\centering
\begin{tabular}[t]{l|l|l|r|r}
\hline
variable & clase & tipo & faltantes & valores\_unicos\\
\hline
\cellcolor{gray!10}{cemento} & \cellcolor{gray!10}{numeric} & \cellcolor{gray!10}{double} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{280}\\
\hline
escoria & numeric & double & 0 & 187\\
\hline
\cellcolor{gray!10}{ceniza} & \cellcolor{gray!10}{numeric} & \cellcolor{gray!10}{double} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{163}\\
\hline
agua & numeric & double & 0 & 205\\
\hline
\cellcolor{gray!10}{superplast} & \cellcolor{gray!10}{numeric} & \cellcolor{gray!10}{double} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{155}\\
\hline
agregado\_grueso & numeric & double & 0 & 284\\
\hline
\cellcolor{gray!10}{agregado\_fino} & \cellcolor{gray!10}{numeric} & \cellcolor{gray!10}{double} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{304}\\
\hline
edad & numeric & double & 0 & 14\\
\hline
\cellcolor{gray!10}{resistencia} & \cellcolor{gray!10}{numeric} & \cellcolor{gray!10}{double} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{938}\\
\hline
\end{tabular}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{duplicados }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{indicador =} \StringTok{"Filas duplicadas"}\NormalTok{,}
  \AttributeTok{cantidad =} \FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(df\_clean))}
\NormalTok{)}

\NormalTok{duplicados }\SpecialCharTok{|\textgreater{}}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Filas duplicadas del conjunto de datos"}\NormalTok{,}
    \AttributeTok{format =} \FunctionTok{ifelse}\NormalTok{(knitr}\SpecialCharTok{::}\FunctionTok{is\_latex\_output}\NormalTok{(), }\StringTok{"latex"}\NormalTok{, }\StringTok{"html"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{),}
    \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{\label{tab:calidad-datos}Filas duplicadas del conjunto de datos}
\centering
\begin{tabular}[t]{l|r}
\hline
indicador & cantidad\\
\hline
\cellcolor{gray!10}{Filas duplicadas} & \cellcolor{gray!10}{25}\\
\hline
\end{tabular}
\end{table}

\section{Tabla descriptiva de las variables}\label{tabla-descriptiva-de-las-variables}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_descriptiva }\OtherTok{\textless{}{-}}\NormalTok{ df\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{pivot\_longer}\NormalTok{(}
    \AttributeTok{cols =} \FunctionTok{everything}\NormalTok{(),}
    \AttributeTok{names\_to =} \StringTok{"variable"}\NormalTok{,}
    \AttributeTok{values\_to =} \StringTok{"valor"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(variable) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n =} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(valor)),}
    \AttributeTok{media =} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{mediana =} \FunctionTok{median}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{RIC =} \FunctionTok{IQR}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{Q1 =} \FunctionTok{quantile}\NormalTok{(valor, }\FloatTok{0.25}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{Q3 =} \FunctionTok{quantile}\NormalTok{(valor, }\FloatTok{0.75}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{minimo =} \FunctionTok{min}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{maximo =} \FunctionTok{max}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{asim =} \FunctionTok{skewness}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{curtosis =} \FunctionTok{kurtosis}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\NormalTok{tabla\_descriptiva }\SpecialCharTok{|\textgreater{}}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Estadisticas descriptivas de las nueve variables"}\NormalTok{,}
    \AttributeTok{digits =} \DecValTok{3}\NormalTok{,}
    \AttributeTok{format =} \FunctionTok{ifelse}\NormalTok{(knitr}\SpecialCharTok{::}\FunctionTok{is\_latex\_output}\NormalTok{(), }\StringTok{"latex"}\NormalTok{, }\StringTok{"html"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{, }\StringTok{"scale\_down"}\NormalTok{),}
    \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{\label{tab:tabla-descriptiva}Estadisticas descriptivas de las nueve variables}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r|r|r}
\hline
variable & n & media & sd & mediana & RIC & Q1 & Q3 & minimo & maximo & asim & curtosis\\
\hline
\cellcolor{gray!10}{agregado\_fino} & \cellcolor{gray!10}{1030} & \cellcolor{gray!10}{773.579} & \cellcolor{gray!10}{80.175} & \cellcolor{gray!10}{779.510} & \cellcolor{gray!10}{93.050} & \cellcolor{gray!10}{730.950} & \cellcolor{gray!10}{824.000} & \cellcolor{gray!10}{594.000} & \cellcolor{gray!10}{992.600} & \cellcolor{gray!10}{-0.253} & \cellcolor{gray!10}{2.893}\\
\hline
agregado\_grueso & 1030 & 972.919 & 77.754 & 968.000 & 97.400 & 932.000 & 1029.400 & 801.000 & 1145.000 & -0.040 & 2.398\\
\hline
\cellcolor{gray!10}{agua} & \cellcolor{gray!10}{1030} & \cellcolor{gray!10}{181.566} & \cellcolor{gray!10}{21.356} & \cellcolor{gray!10}{185.000} & \cellcolor{gray!10}{27.100} & \cellcolor{gray!10}{164.900} & \cellcolor{gray!10}{192.000} & \cellcolor{gray!10}{121.750} & \cellcolor{gray!10}{247.000} & \cellcolor{gray!10}{0.074} & \cellcolor{gray!10}{3.116}\\
\hline
cemento & 1030 & 281.166 & 104.507 & 272.900 & 157.625 & 192.375 & 350.000 & 102.000 & 540.000 & 0.509 & 2.476\\
\hline
\cellcolor{gray!10}{ceniza} & \cellcolor{gray!10}{1030} & \cellcolor{gray!10}{54.187} & \cellcolor{gray!10}{63.996} & \cellcolor{gray!10}{0.000} & \cellcolor{gray!10}{118.270} & \cellcolor{gray!10}{0.000} & \cellcolor{gray!10}{118.270} & \cellcolor{gray!10}{0.000} & \cellcolor{gray!10}{200.100} & \cellcolor{gray!10}{0.537} & \cellcolor{gray!10}{1.672}\\
\hline
edad & 1030 & 45.662 & 63.170 & 28.000 & 49.000 & 7.000 & 56.000 & 1.000 & 365.000 & 3.264 & 15.104\\
\hline
\cellcolor{gray!10}{escoria} & \cellcolor{gray!10}{1030} & \cellcolor{gray!10}{73.895} & \cellcolor{gray!10}{86.279} & \cellcolor{gray!10}{22.000} & \cellcolor{gray!10}{142.950} & \cellcolor{gray!10}{0.000} & \cellcolor{gray!10}{142.950} & \cellcolor{gray!10}{0.000} & \cellcolor{gray!10}{359.400} & \cellcolor{gray!10}{0.800} & \cellcolor{gray!10}{2.489}\\
\hline
resistencia & 1030 & 35.818 & 16.706 & 34.443 & 22.429 & 23.707 & 46.136 & 2.332 & 82.599 & 0.416 & 2.682\\
\hline
\cellcolor{gray!10}{superplast} & \cellcolor{gray!10}{1030} & \cellcolor{gray!10}{6.203} & \cellcolor{gray!10}{5.973} & \cellcolor{gray!10}{6.350} & \cellcolor{gray!10}{10.160} & \cellcolor{gray!10}{0.000} & \cellcolor{gray!10}{10.160} & \cellcolor{gray!10}{0.000} & \cellcolor{gray!10}{32.200} & \cellcolor{gray!10}{0.907} & \cellcolor{gray!10}{4.401}\\
\hline
\end{tabular}}
\end{table}

\subsection{Exploración de la variable de respuesta}\label{exploraciuxf3n-de-la-variable-de-respuesta}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_resistencia }\OtherTok{\textless{}{-}}\NormalTok{ df\_clean }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n =} \FunctionTok{length}\NormalTok{(resistencia),}
                 \AttributeTok{media =} \FunctionTok{mean}\NormalTok{(resistencia),}
                 \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(resistencia),}
                 \AttributeTok{mediana =} \FunctionTok{median}\NormalTok{(resistencia),}
                 \AttributeTok{RIC =} \FunctionTok{IQR}\NormalTok{(resistencia),}
                 \AttributeTok{Q1 =} \FunctionTok{quantile}\NormalTok{(resistencia, }\FloatTok{0.25}\NormalTok{),}
                 \AttributeTok{Q3 =} \FunctionTok{quantile}\NormalTok{(resistencia, }\FloatTok{0.75}\NormalTok{),}
                 \AttributeTok{minimo =} \FunctionTok{min}\NormalTok{(resistencia),}
                 \AttributeTok{maximo =} \FunctionTok{max}\NormalTok{(resistencia),}
                 \AttributeTok{asim =} \FunctionTok{skewness}\NormalTok{(resistencia),}
                 \AttributeTok{curtosis =} \FunctionTok{kurtosis}\NormalTok{(resistencia))}

\NormalTok{tabla\_resistencia }\SpecialCharTok{|\textgreater{}}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Estadisticas descriptivas de la resistencia a la compresion"}\NormalTok{,}
    \AttributeTok{digits =} \DecValTok{3}\NormalTok{,}
    \AttributeTok{format =} \FunctionTok{ifelse}\NormalTok{(knitr}\SpecialCharTok{::}\FunctionTok{is\_latex\_output}\NormalTok{(), }\StringTok{"latex"}\NormalTok{, }\StringTok{"html"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{, }\StringTok{"scale\_down"}\NormalTok{),}
    \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{(\#tab:Concrete Compressive strenght)Estadisticas descriptivas de la resistencia a la compresion}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{r|r|r|r|r|r|r|r|r|r|r}
\hline
n & media & sd & mediana & RIC & Q1 & Q3 & minimo & maximo & asim & curtosis\\
\hline
\cellcolor{gray!10}{1030} & \cellcolor{gray!10}{35.818} & \cellcolor{gray!10}{16.706} & \cellcolor{gray!10}{34.443} & \cellcolor{gray!10}{22.429} & \cellcolor{gray!10}{23.707} & \cellcolor{gray!10}{46.136} & \cellcolor{gray!10}{2.332} & \cellcolor{gray!10}{82.599} & \cellcolor{gray!10}{0.416} & \cellcolor{gray!10}{2.682}\\
\hline
\end{tabular}}
\end{table}

Vemos que las 1030 observaciones de mezclas de concreto, tienen una resistencia de comprension de 35.817 MPa, con una desviación estándar de 16.70 MPa. Además, el 50\% de las mezclas tienen una resistencia igual o menor a 34.442 MPa. Además, se observa una mezcla de concreto experimental con resistencia de 85.59 MPa siendo esta la observación con mayor Resistencia final a la compresión y otras con la minima resistencia entre las observaciones con 2.33 MPa.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{options}\NormalTok{(}\AttributeTok{scipen =} \DecValTok{999}\NormalTok{)}
\NormalTok{df\_clean }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ resistencia)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(density)),}
    \AttributeTok{binwidth =} \DecValTok{2}\NormalTok{,}
    \AttributeTok{fill =} \StringTok{"darkblue"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"white"}\NormalTok{,}
    \AttributeTok{alpha =} \FloatTok{0.6}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"darkblue"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Distribución de la resistencia del concreto"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Resistencia"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Densidad"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-3-1} \end{center}

la resistencia muestra una distribución con forma parecida a una \textbf{simétrica con forma de campana}, centrada en torno a los \(35\text{ MPa}\) y abarcando un rango desde los \(2.3\) hasta los \(82.6\text{ MPa}\). La curva de densidad sugiere un comportamiento cercano a la \textbf{distribución normal}, reflejando una muestra equilibrada que abarca desde concretos convencionales hasta mezclas de alto rendimiento.
\#\# Exploracion de las varibles independientes

Creamos la siguiente tabla para observar de forma descriptiva las variables independientes que analizaremos y asi complementar el analisis de los boxplots con ella.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_independientes }\OtherTok{\textless{}{-}}\NormalTok{ df\_clean }\SpecialCharTok{|\textgreater{}} \FunctionTok{select}\NormalTok{(ceniza, edad) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{pivot\_longer}\NormalTok{(}
    \AttributeTok{cols =} \FunctionTok{everything}\NormalTok{(),}
    \AttributeTok{names\_to =} \StringTok{\textquotesingle{}variables\textquotesingle{}}\NormalTok{,}
    \AttributeTok{values\_to =} \StringTok{\textquotesingle{}valor\textquotesingle{}}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{group\_by}\NormalTok{(variables) }\SpecialCharTok{|\textgreater{}} 
             \FunctionTok{summarise}\NormalTok{(    }
    \AttributeTok{n =} \FunctionTok{length}\NormalTok{(valor),}
    \AttributeTok{media =} \FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(valor), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{sd =} \FunctionTok{round}\NormalTok{(}\FunctionTok{sd}\NormalTok{(valor),}\DecValTok{3}\NormalTok{),}
    \AttributeTok{mediana =} \FunctionTok{round}\NormalTok{(}\FunctionTok{median}\NormalTok{(valor), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{RIC =} \FunctionTok{round}\NormalTok{(}\FunctionTok{IQR}\NormalTok{(valor), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{Q1 =} \FunctionTok{round}\NormalTok{(}\FunctionTok{quantile}\NormalTok{(valor, }\FloatTok{0.25}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{Q3 =} \FunctionTok{round}\NormalTok{(}\FunctionTok{quantile}\NormalTok{(valor, }\FloatTok{0.75}\NormalTok{), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{minimo  =} \FunctionTok{round}\NormalTok{(}\FunctionTok{min}\NormalTok{(valor), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{maximo  =} \FunctionTok{round}\NormalTok{(}\FunctionTok{max}\NormalTok{(valor), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{asim    =} \FunctionTok{round}\NormalTok{(}\FunctionTok{skewness}\NormalTok{(valor), }\DecValTok{3}\NormalTok{),}
    \AttributeTok{curtosis =} \FunctionTok{round}\NormalTok{(}\FunctionTok{kurtosis}\NormalTok{(valor), }\DecValTok{3}\NormalTok{))}

\NormalTok{tabla\_independientes }\SpecialCharTok{|\textgreater{}}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Estadisticas descriptivas de ceniza volante y edad"}\NormalTok{,}
    \AttributeTok{digits =} \DecValTok{3}\NormalTok{,}
    \AttributeTok{format =} \FunctionTok{ifelse}\NormalTok{(knitr}\SpecialCharTok{::}\FunctionTok{is\_latex\_output}\NormalTok{(), }\StringTok{"latex"}\NormalTok{, }\StringTok{"html"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{, }\StringTok{"scale\_down"}\NormalTok{),}
    \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{\label{tab:unnamed-chunk-4}Estadisticas descriptivas de ceniza volante y edad}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|r|r|r|r|r|r|r|r|r|r|r}
\hline
variables & n & media & sd & mediana & RIC & Q1 & Q3 & minimo & maximo & asim & curtosis\\
\hline
\cellcolor{gray!10}{ceniza} & \cellcolor{gray!10}{1030} & \cellcolor{gray!10}{54.187} & \cellcolor{gray!10}{63.996} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{118.27} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{118.27} & \cellcolor{gray!10}{0} & \cellcolor{gray!10}{200.1} & \cellcolor{gray!10}{0.537} & \cellcolor{gray!10}{1.672}\\
\hline
edad & 1030 & 45.662 & 63.170 & 28 & 49.00 & 7 & 56.00 & 1 & 365.0 & 3.264 & 15.104\\
\hline
\end{tabular}}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ ceniza)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(density)),}
    \AttributeTok{binwidth =} \DecValTok{10}\NormalTok{,           }\CommentTok{\# Intervalos de 10 kg/m\^{}3}
    \AttributeTok{fill =} \StringTok{"\#d95f02"}\NormalTok{,        }\CommentTok{\# Tono naranja / teja}
    \AttributeTok{color =} \StringTok{"white"}\NormalTok{,}
    \AttributeTok{alpha =} \FloatTok{0.6}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"\#d95f02"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Distribución del contenido de Ceniza Volante"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Ceniza Volante (kg/m³)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Densidad"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-5-1} \end{center}

La distribución es fuertemente bimodal e inflada en ceros. Presenta una concentración masiva en los \(0\text{ kg/m}^3\) correspondiente a las mezclas tradicionales de control (\(55\%\) de la muestra), seguida de un segundo agrupamiento entre los \(80\) y \(160\text{ kg/m}^3\) en aquellas formulaciones donde sí se sustituyó cemento por ceniza. Esta notable asimetría y falta de continuidad confirma la \textbf{no normalidad} de la variabl.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ edad)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(density)),}
    \AttributeTok{binwidth =} \DecValTok{14}\NormalTok{,           }\CommentTok{\# Intervalos de 14 días (2 semanas)}
    \AttributeTok{fill =} \StringTok{"\#7570b3"}\NormalTok{,        }\CommentTok{\# Tono violeta}
    \AttributeTok{color =} \StringTok{"white"}\NormalTok{,}
    \AttributeTok{alpha =} \FloatTok{0.6}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color =} \StringTok{"\#7570b3"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{1.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Distribución del Tiempo de Curado"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Tiempo de Curado (Días)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Densidad"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-6-1} \end{center}

La distribución exhibe un marcado sesgo positivo con picos, concentrando la gran mayoría de las observaciones en los \(28\text{ días}\) la cual es la edad estándar de diseño y en periodos tempranos (\(\le 7\text{ días}\)). La densidad decae drásticamente a partir de los \(56\text{ días}\), extendiéndose en una cola larga hasta los \(365\text{ días}\), lo cual evidencia una distribución \textbf{no normal} explicada por el diseño experimental enfocado en etapas normativas de obra.

\section{Anlisis Univariado de las variables}\label{anlisis-univariado-de-las-variables}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 1. Boxplot de Ceniza Volante}
\NormalTok{p1 }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =} \StringTok{\textasciigrave{}}\AttributeTok{Fly Ash (component 3)(kg in a m\^{}3 mixture)}\StringTok{\textasciigrave{}}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \StringTok{"\#d62728"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Ceniza Volante (Fly Ash)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Ceniza Volante (kg/m³)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{""}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}


\CommentTok{\# 2. Boxplot de Edad de Curado}
\NormalTok{p2 }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =} \StringTok{\textasciigrave{}}\AttributeTok{Age (day)}\StringTok{\textasciigrave{}}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \StringTok{"\#e377c2"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Tiempo de Curado"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Edad (Días)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{""}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}

\CommentTok{\# 3. Boxplot de Resistencia a la Compresión (Target / Variable Respuesta)}
\NormalTok{p3 }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =} \StringTok{\textasciigrave{}}\AttributeTok{Concrete compressive strength(MPa, megapascals)}\StringTok{\textasciigrave{}}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \StringTok{"\#bcbd22"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Resistencia a la Compresión"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Resistencia (MPa)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{""}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1 }
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-7-1} \end{center}

\subsection{Analisis boxplot Fly Ash}\label{analisis-boxplot-fly-ash}

Se observa una distribución atipica con alta dispersión de los datos, además por la tabla anterior la media del uso de ceniza en las mezclas es \(54.2 kg/m^3\) y una desviación estándar de \(64 kg/m^3\)

Sin embargo el diagrama de caja muestra que el 50\% de los valores de ceniza coincide con el limite inferior, esto indica que el 50\% de las mezclas no contienen contienen ceniza volante. Por otra parte, el 75\% de las observaciones contienen una cantidad de ceniza menor o igual a \(118.6 kg/m^3\), mientras que el migote señala mezclas con un maximo de \(201.1 kg/m^3\), no se evidencia ningun valor atipico.

¿porque hay este comportamiento de los datos centrado en cero?
esto se debe a que el conjunto de datos contiene mezclas de control convencionales elaboradas exclusivamente con cemento tradicional para servir de base comparativa. Por ende, la ceniza volante actúa como un componente opcional.

\subsection{Analisis boxplot tiempo de curado}\label{analisis-boxplot-tiempo-de-curado}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-8-1} \end{center}

La variable \(\text{Age}\) (días de curado) presenta una concentración en edades tempranas y unagran dispersión, reflejada en un tiempo promedio de curado de \(45.7\text{ días}\) y una desviación estándar de \(63.2\text{ días}\).

El boxplot nos permite observar una distribución sesgada a la derecha, tambien el \(50\%\) de las muestras fueron ensayadas a los \(28\text{ días}\) o menos, el \(25\%\) inferior corresponde a edades tempranas iguales o menores a \(7\text{ días}\), y el \(75\%\) central se concentra por debajo de los \(56\text{ días}\). No obstante, el diagrama de caja evidencia una serie de \textbf{valores extremos} en la parte superior, con esayos a los \(90\), \(180\), \(270\) y hasta un máximo de \(365\text{ días}\) es decir un año completo de curado.

\textbf{¿Por qué existen valores atípicos tan elevados?}\\
En la práctica de la ingeniería civil, los ensayos estándar de control de calidad se realizan de forma rutinaria a los \(7\), \(14\) y principalmente a los \(28\text{ días}\). Los tiempos de curado prolongados (\(> 90\text{ días}\)) son ensayos de investigación concebidos para evaluar la durabilidad a largo plazo y la reacción tardía de adiciones minerales como la ceniza volante.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p3}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-9-1} \end{center}

Para la variable objetivo ``resistencia'', se observa un comportamiento mucho más homogéneo y balanceado, con un promedio de resistencia de \(35.8\text{ MPa}\) y una desviación estándar de \(16.7\text{ MPa}\).

El 50\% de los datos tienen una resistencia menor o igual a \(34.5\text{ MPa}\), mostrando una \textbf{notable cercanía con el promedio de resistencia de las mezclas de concreto (\(35.8\text{ MPa}\))}. En cuanto al rango intercuartílico, el \(25\%\) de las mezclas con menor resistencia registran valores iguales o inferiores a \(23.7\text{ MPa}\), mientras que el \(75\%\) de las muestras se sitúan por debajo de los \(46.1\text{ MPa}\). Los bigotes abarcan un rango que va desde un mínimo de \(2.3\text{ MPa}\) (concreto de muy baja resistencia) hasta aproximadamente los \(80.0\text{ MPa}\). Se aprecian únicamente unos pocos \textbf{valores atípicos superiores} que alcanzan un máximo de \(82.6\text{ MPa}\).

\section{Analisis Bivariado}\label{analisis-bivariado}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{ggpairs}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-10-1} \end{center}

\subsection{Creacion de nuevas variables}\label{creacion-de-nuevas-variables}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_fe }\OtherTok{\textless{}{-}}\NormalTok{ df\_clean }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{(}
    \CommentTok{\# 1. Razón Agua / Cementante (Agua / [Cemento + Ceniza])}
    \AttributeTok{razon\_agua\_cementante =}\NormalTok{ agua }\SpecialCharTok{/}\NormalTok{ (cemento }\SpecialCharTok{+}\NormalTok{ ceniza),}
    
    \CommentTok{\# 2. Porcentaje de Cemento sustituido por Ceniza (0\% a \textasciitilde{}50\%)}
    \AttributeTok{pct\_ceniza =}\NormalTok{ (ceniza }\SpecialCharTok{/}\NormalTok{ (cemento }\SpecialCharTok{+}\NormalTok{ ceniza)) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    
    \CommentTok{\# 3. Clasificación del reemplazo en niveles (para futuros ANOVAs)}
    \AttributeTok{nivel\_ceniza =} \FunctionTok{factor}\NormalTok{(}\FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      pct\_ceniza }\SpecialCharTok{==} \DecValTok{0} \SpecialCharTok{\textasciitilde{}} \StringTok{"0\% (Control)"}\NormalTok{,}
\NormalTok{      pct\_ceniza }\SpecialCharTok{\textgreater{}} \DecValTok{0} \SpecialCharTok{\&}\NormalTok{ pct\_ceniza }\SpecialCharTok{\textless{}=} \DecValTok{20} \SpecialCharTok{\textasciitilde{}} \StringTok{"Bajo (\textless{}= 20\%)"}\NormalTok{,}
\NormalTok{      pct\_ceniza }\SpecialCharTok{\textgreater{}} \DecValTok{20} \SpecialCharTok{\textasciitilde{}} \StringTok{"Alto (\textgreater{} 20\%)"}
\NormalTok{    ), }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"0\% (Control)"}\NormalTok{, }\StringTok{"Bajo (\textless{}= 20\%)"}\NormalTok{, }\StringTok{"Alto (\textgreater{} 20\%)"}\NormalTok{)),}
    
    \CommentTok{\# 4. Transformación Logarítmica de la Edad (Linealiza la ganancia de resistencia)}
    \AttributeTok{log\_edad =} \FunctionTok{log}\NormalTok{(edad),}
    
    \CommentTok{\# 5. Etapas estándar de curado}
    \AttributeTok{etapa\_curado =} \FunctionTok{factor}\NormalTok{(}\FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      edad }\SpecialCharTok{\textless{}=} \DecValTok{7} \SpecialCharTok{\textasciitilde{}} \StringTok{"Temprano (\textless{}= 7d)"}\NormalTok{,}
\NormalTok{      edad }\SpecialCharTok{\textgreater{}} \DecValTok{7} \SpecialCharTok{\&}\NormalTok{ edad }\SpecialCharTok{\textless{}=} \DecValTok{28} \SpecialCharTok{\textasciitilde{}} \StringTok{"Estándar (14{-}28d)"}\NormalTok{,}
\NormalTok{      edad }\SpecialCharTok{\textgreater{}} \DecValTok{28} \SpecialCharTok{\textasciitilde{}} \StringTok{"Tardío (\textgreater{} 28d)"}
\NormalTok{    ), }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Temprano (\textless{}= 7d)"}\NormalTok{, }\StringTok{"Estándar (14{-}28d)"}\NormalTok{, }\StringTok{"Tardío (\textgreater{} 28d)"}\NormalTok{))}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\subsection{Tabla descriptiva de las nuevas variables}\label{tabla-descriptiva-de-las-nuevas-variables}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_nuevas\_numericas }\OtherTok{\textless{}{-}}\NormalTok{ df\_fe }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(razon\_agua\_cementante, pct\_ceniza, log\_edad) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{pivot\_longer}\NormalTok{(}
    \AttributeTok{cols =} \FunctionTok{everything}\NormalTok{(),}
    \AttributeTok{names\_to =} \StringTok{"variable"}\NormalTok{,}
    \AttributeTok{values\_to =} \StringTok{"valor"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(variable) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n =} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(valor)),}
    \AttributeTok{media =} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{mediana =} \FunctionTok{median}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{minimo =} \FunctionTok{min}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{maximo =} \FunctionTok{max}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{asim =} \FunctionTok{skewness}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{curtosis =} \FunctionTok{kurtosis}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\NormalTok{tabla\_nuevas\_numericas }\SpecialCharTok{|\textgreater{}}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Estadisticas descriptivas de las nuevas variables numericas"}\NormalTok{,}
    \AttributeTok{digits =} \DecValTok{3}\NormalTok{,}
    \AttributeTok{format =} \FunctionTok{ifelse}\NormalTok{(knitr}\SpecialCharTok{::}\FunctionTok{is\_latex\_output}\NormalTok{(), }\StringTok{"latex"}\NormalTok{, }\StringTok{"html"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{, }\StringTok{"scale\_down"}\NormalTok{),}
    \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{\label{tab:tabla-nuevas-variables-numericas}Estadisticas descriptivas de las nuevas variables numericas}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{l|r|r|r|r|r|r|r|r}
\hline
variable & n & media & sd & mediana & minimo & maximo & asim & curtosis\\
\hline
\cellcolor{gray!10}{log\_edad} & \cellcolor{gray!10}{1030} & \cellcolor{gray!10}{3.165} & \cellcolor{gray!10}{1.191} & \cellcolor{gray!10}{3.332} & \cellcolor{gray!10}{0.000} & \cellcolor{gray!10}{5.900} & \cellcolor{gray!10}{-0.151} & \cellcolor{gray!10}{2.642}\\
\hline
pct\_ceniza & 1030 & 15.526 & 18.788 & 0.000 & 0.000 & 58.841 & 0.649 & 1.859\\
\hline
\cellcolor{gray!10}{razon\_agua\_cementante} & \cellcolor{gray!10}{1030} & \cellcolor{gray!10}{0.612} & \cellcolor{gray!10}{0.278} & \cellcolor{gray!10}{0.548} & \cellcolor{gray!10}{0.266} & \cellcolor{gray!10}{1.882} & \cellcolor{gray!10}{1.965} & \cellcolor{gray!10}{7.529}\\
\hline
\end{tabular}}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_nuevas\_categoricas }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(}
\NormalTok{  df\_fe }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{count}\NormalTok{(nivel\_ceniza, }\AttributeTok{name =} \StringTok{"frecuencia"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{transmute}\NormalTok{(}\AttributeTok{variable =} \StringTok{"nivel\_ceniza"}\NormalTok{, }\AttributeTok{categoria =} \FunctionTok{as.character}\NormalTok{(nivel\_ceniza), frecuencia),}
\NormalTok{  df\_fe }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{count}\NormalTok{(etapa\_curado, }\AttributeTok{name =} \StringTok{"frecuencia"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{transmute}\NormalTok{(}\AttributeTok{variable =} \StringTok{"etapa\_curado"}\NormalTok{, }\AttributeTok{categoria =} \FunctionTok{as.character}\NormalTok{(etapa\_curado), frecuencia)}
\NormalTok{)}

\NormalTok{tabla\_nuevas\_categoricas }\SpecialCharTok{|\textgreater{}}
\NormalTok{  knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Frecuencias de las nuevas variables categoricas"}\NormalTok{,}
    \AttributeTok{format =} \FunctionTok{ifelse}\NormalTok{(knitr}\SpecialCharTok{::}\FunctionTok{is\_latex\_output}\NormalTok{(), }\StringTok{"latex"}\NormalTok{, }\StringTok{"html"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hover"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{),}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{),}
    \AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{table}[!h]
\centering
\caption{\label{tab:tabla-nuevas-variables-categoricas}Frecuencias de las nuevas variables categoricas}
\centering
\begin{tabular}[t]{l|l|r}
\hline
variable & categoria & frecuencia\\
\hline
\cellcolor{gray!10}{nivel\_ceniza} & \cellcolor{gray!10}{0\% (Control)} & \cellcolor{gray!10}{566}\\
\hline
nivel\_ceniza & Bajo (<= 20\%) & 43\\
\hline
\cellcolor{gray!10}{nivel\_ceniza} & \cellcolor{gray!10}{Alto (> 20\%)} & \cellcolor{gray!10}{421}\\
\hline
etapa\_curado & Temprano (<= 7d) & 262\\
\hline
\cellcolor{gray!10}{etapa\_curado} & \cellcolor{gray!10}{Estándar (14-28d)} & \cellcolor{gray!10}{487}\\
\hline
etapa\_curado & Tardío (> 28d) & 281\\
\hline
\end{tabular}
\end{table}

\section{Pruebas de normalidad}\label{pruebas-de-normalidad}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-} 1. PRUEBAS ESTADÍSTICAS DE NORMALIDAD {-}{-}{-}}

\CommentTok{\# Prueba de Shapiro{-}Wilk para la variable de respuesta}
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{resistencia)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$resistencia
## W = 0.97979, p-value = 0.00000000009023
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Prueba de Shapiro{-}Wilk para las variables independientes}
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{ceniza)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$ceniza
## W = 0.76201, p-value < 0.00000000000000022
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{edad)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$edad
## W = 0.59071, p-value < 0.00000000000000022
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{cemento)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$cemento
## W = 0.95896, p-value < 0.00000000000000022
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{agua)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$agua
## W = 0.9804, p-value = 0.0000000001473
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{agregado\_grueso)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$agregado_grueso
## W = 0.98245, p-value = 0.0000000008346
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{lapply}\NormalTok{(df\_clean, shapiro.test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $cemento
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.95896, p-value < 0.00000000000000022
## 
## 
## $escoria
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.81241, p-value < 0.00000000000000022
## 
## 
## $ceniza
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.76201, p-value < 0.00000000000000022
## 
## 
## $agua
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.9804, p-value = 0.0000000001473
## 
## 
## $superplast
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.86605, p-value < 0.00000000000000022
## 
## 
## $agregado_grueso
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.98245, p-value = 0.0000000008346
## 
## 
## $agregado_fino
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.98067, p-value = 0.0000000001843
## 
## 
## $edad
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.59071, p-value < 0.00000000000000022
## 
## 
## $resistencia
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.97979, p-value = 0.00000000009023
\end{verbatim}

\subsection{2. VALIDACIÓN VISUAL (Q-Q PLOTS)}\label{validaciuxf3n-visual-q-q-plots}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Gráfico para la Resistencia}
\FunctionTok{qqnorm}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{resistencia, }\AttributeTok{pch =} \DecValTok{1}\NormalTok{, }\AttributeTok{frame =} \ConstantTok{FALSE}\NormalTok{, }
       \AttributeTok{main =} \StringTok{"Gráfico Q{-}Q: Resistencia a la Compresión"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{resistencia, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-13-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Gráfico para la Edad}
\FunctionTok{qqnorm}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{edad, }\AttributeTok{pch =} \DecValTok{1}\NormalTok{, }\AttributeTok{frame =} \ConstantTok{FALSE}\NormalTok{, }
       \AttributeTok{main =} \StringTok{"Gráfico Q{-}Q: Tiempo de Curado (Edad)"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{edad, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-13-2} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Interpretación del Gráfico Q-Q para la Resistencia a la Compresión
\end{enumerate}

Comportamiento central: En el centro del gráfico, la gran mayoría de los puntos se alinean bastante bien sobre la línea diagonal roja. Esto indica que los valores medios de resistencia (alrededor de los 35 MPa) tienen un comportamiento muy cercano a una distribución simétrica normal.

Desviación en los extremos (Colas): El gráfico seguramente muestra que los puntos se separan ligeramente de la línea roja en el extremo inferior (esquina inferior izquierda) y en el extremo superior (esquina superior derecha).

Conclusión: Esta pequeña desviación en los extremos es típica de variables que están acotadas (la resistencia no puede ser negativa) o que tienen unos pocos valores atípicamente altos (mezclas de muy alto rendimiento). Esto concuerda con tu prueba de Shapiro-Wilk (\(W = 0.97979\)), donde la variable se ve ``casi'' normal en el centro, pero las ligeras desviaciones en las colas hacen que la prueba estadística la rechace matemáticamente.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Pruebas estadísticas (Shapiro{-}Wilk)}
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{cemento)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$cemento
## W = 0.95896, p-value < 0.00000000000000022
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{agua)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$agua
## W = 0.9804, p-value = 0.0000000001473
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{agregado\_grueso)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  df_clean$agregado_grueso
## W = 0.98245, p-value = 0.0000000008346
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# (Puedes copiar y pegar para el resto de variables)}

\CommentTok{\# Aplicar Shapiro{-}Wilk a todas las columnas de df\_clean de un solo golpe}
\NormalTok{resultados\_normalidad }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(df\_clean, shapiro.test)}
\NormalTok{resultados\_normalidad}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $cemento
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.95896, p-value < 0.00000000000000022
## 
## 
## $escoria
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.81241, p-value < 0.00000000000000022
## 
## 
## $ceniza
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.76201, p-value < 0.00000000000000022
## 
## 
## $agua
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.9804, p-value = 0.0000000001473
## 
## 
## $superplast
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.86605, p-value < 0.00000000000000022
## 
## 
## $agregado_grueso
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.98245, p-value = 0.0000000008346
## 
## 
## $agregado_fino
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.98067, p-value = 0.0000000001843
## 
## 
## $edad
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.59071, p-value < 0.00000000000000022
## 
## 
## $resistencia
## 
##  Shapiro-Wilk normality test
## 
## data:  X[[i]]
## W = 0.97979, p-value = 0.00000000009023
\end{verbatim}

Al evaluar las nueve variables del conjunto de datos mediante la prueba de normalidad de Shapiro-Wilk, se obtienen las siguientes conclusiones estadísticas para documentar en tu Análisis Exploratorio de Datos (EDA):

Rechazo generalizado de la normalidad: Todas las variables analizadas arrojaron un p-valor estrictamente inferior al nivel de significancia de \(0.05\). En consecuencia, se rechaza la hipótesis nula (\(H_0\)) para todo el conjunto de datos y se concluye estadísticamente que ninguna variable sigue una distribución normal perfecta.

Variables con desviación severa (Alta asimetría o inflación de ceros): Las variables edad (\(W = 0.59071\)), ceniza (\(W = 0.76201\)), escoria (\(W = 0.81241\)) y superplast (\(W = 0.86605\)) presentan las violaciones más fuertes al supuesto de normalidad, reflejadas en los estadísticos \(W\) más bajos y p-valores menores a \(0.00000000000000022\). Esto corrobora el análisis gráfico preliminar: la edad tiene saltos marcados por los tiempos estándar de curado, mientras que los aditivos presentan una enorme concentración de ceros (mezclas que no los incluyen).

Variables con aproximación a la normalidad (Sensibilidad de la prueba): Las variables agregado\_grueso (\(W = 0.98245\)), agregado\_fino (\(W = 0.98067\)), agua (\(W = 0.9804\)), resistencia (\(W = 0.97979\)) y cemento (\(W = 0.95896\)) poseen un estadístico \(W\) muy cercano a \(1\). Aunque sus p-valores obligan a rechazar la normalidad teórica (fluctuando en el orden de \(10^{-10}\) a \(10^{-12}\)), la estructura de sus datos es razonablemente simétrica y acampanada. El rechazo se explica principalmente por la hipersensibilidad de la prueba de Shapiro-Wilk ante tamaños de muestra grandes (\(N=1030\)), donde cualquier desviación milimétrica de la campana de Gauss resulta estadísticamente significativa.

Impacto metodológico para el modelo: Dado que las variables no son normales por naturaleza, no se recomienda utilizar correlaciones paramétricas simples (como Pearson) para medir sus relaciones, sino alternativas robustas como la correlación de Spearman. Además, la regresión múltiple exigirá validar la normalidad directamente sobre los residuos predictivos y no sobre estas variables independientes aisladas, contemplando posibles transformaciones logarítmicas para las variables del primer grupo (edad y aditivos).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Gráficos Q{-}Q para ver visualmente la distribución}
\FunctionTok{qqnorm}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{agua, }\AttributeTok{pch =} \DecValTok{1}\NormalTok{, }\AttributeTok{frame =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{main =} \StringTok{"Gráfico Q{-}Q: Cantidad de Agua"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{agua, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-15-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{cemento, }\AttributeTok{pch =} \DecValTok{1}\NormalTok{, }\AttributeTok{frame =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{main =} \StringTok{"Gráfico Q{-}Q: Cemento"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{cemento, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Proyecto_Final_Metodos_Estadisticos_files/figure-latex/unnamed-chunk-15-2} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Interpretación del Gráfico Q-Q para el Tiempo de Curado (Edad)
\end{enumerate}

Falta de alineación y forma de ``escalera'': Al mirar este gráfico, los puntos no siguen una línea recta continua. En su lugar, vas a ver agrupaciones densas de puntos dispuestas de forma horizontal (como si fueran escalones) y muy separadas de la línea roja de referencia.

Por qué ocurre esto (Asimetría severa): Esta desviación extrema ocurre porque el tiempo de curado no es una variable continua natural en este experimento. Los laboratoristas toman medidas en días fijos normativos (3, 7, 14, 28, 56 días, etc.), creando ``saltos'' en la distribución. Además, como la enorme mayoría de las pruebas se hacen a los 28 días y muy pocas llegan a un año (365 días), la distribución tiene un sesgo altísimo hacia la izquierda.

Conclusión: La trayectoria de los puntos corrobora visualmente el pésimo resultado de su prueba de Shapiro-Wilk (\(W = 0.59071\)). La edad presenta una desviación radical respecto al modelo de campana de Gauss, confirmando una distribución discreta, marcadamente sesgada hacia la derecha (valores tempranos) y con una cola larga.

\bibliography{book.bib}

\end{document}
